AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw ForresaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharcoaltAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw RainerAnimation
	dw GlowurmAnimation
	dw ChrysalunaAnimation
	dw LunaflyAnimation
	dw MininjaAnimation
	dw MidoninjaAnimation
	dw KushinobiAnimation
	dw PipunAnimation
	dw PipawkAnimation
	dw PeregrandeAnimation
	dw RattataPlainAnimation
	dw RaticatePlainAnimation
	dw LepskiAnimation
	dw RabalancheAnimation
	dw EkansAnimation
	dw ArbokJohtoAnimation
	dw PikachuPlainAnimation
	dw RaichuPlainAnimation
	dw SandshrewPlainAnimation
	dw SandslashPlainAnimation
	dw KelppAnimation
	dw SetistaAnimation
	dw FarcystisAnimation
	dw TottemAnimation
	dw TototemAnimation
	dw TotowerAnimation
	dw ToulavAnimation
	dw VollavAnimation
	dw VulpixPlainAnimation
	dw NinetalesPlainAnimation
	dw LunelleAnimation
	dw GazalaxyAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw SpirikAnimation
	dw SpirrentAnimation
	dw GhobraAnimation
	dw AmirokAnimation
	dw KiyarokAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw DiglettPlainAnimation
	dw DugtrioPlainAnimation
	dw OofoePlainAnimation
	dw XterrestrePlainAnimation
	dw OntlamAnimation
	dw BlizzaramAnimation
	dw TaegleAnimation
	dw TaloniteAnimation
	dw ShreekAnimation
	dw JestauntAnimation
	dw TaroxinAnimation
	dw SauroxicAnimation
	dw ChatotAnimation
	dw MiraiAnimation
	dw MiralupeAnimation
	dw MiralairAnimation
	dw SnarligerAnimation
	dw NoctigerAnimation
	dw RaigerAnimation
	dw VenapAnimation
	dw TraplentAnimation
	dw DionareAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudePlainAnimation
	dw GravelerPlainAnimation
	dw GolemPlainAnimation
	dw PonytaPlainAnimation
	dw RapidashPlainAnimation
	dw SlowpokePlainAnimation
	dw SlowbroPlainAnimation
	dw CumosAnimation
	dw AgmosAnimation
	dw OrclataAnimation
	dw SonnestAnimation
	dw CanarosaAnimation
	dw SygnalAnimation
	dw SwanamiAnimation
	dw GrimerPlainAnimation
	dw MukPlainAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw ChitangAnimation
	dw KudangAnimation
	dw TerrangAnimation
	dw OnixAnimation
	dw InfermataAnimation
	dw ClarimataAnimation
	dw TyookAnimation
	dw MorterrorAnimation
	dw VoltotAnimation
	dw ToxicellAnimation
	dw ExeggcuteAnimation
	dw ExeggutorPlainAnimation
	dw CuboneAnimation
	dw MarowakPlainAnimation
	dw MalistrilAnimation
	dw KipporokAnimation
	dw KoffingAnimation
	dw WeezingPlainAnimation
	dw PsibianAnimation
	dw GorphibiusAnimation
	dw ChanseyAnimation
	dw DunviathanAnimation
	dw VolphinAnimation
	dw AquonyAnimation
	dw AquallionAnimation
	dw PhairisAnimation
	dw SprimaAnimation
	dw DrylacAnimation
	dw AbsolAnimation
	dw AbsognoAnimation
	dw SerinaviAnimation
	dw ScytherAnimation
	dw KaramaAnimation
	dw FlarakeAnimation
	dw HelidraAnimation
	dw BrahmosAnimation
	dw TaurosAnimation
	dw MagikarpPlainAnimation
	dw GyaradosPlainAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw IonAnimation
	dw SolarionAnimation
	dw LunarionAnimation
	dw NebulionAnimation
	dw AditankAnimation
	dw InfastegoAnimation
	dw LethastegoAnimation
	dw AnkyloAnimation
	dw AnkyledgeAnimation
	dw GolothAnimation
	dw IllumbraAnimation
	dw ArticunoPlainAnimation
	dw ZapdosPlainAnimation
	dw MoltresPlainAnimation
	dw BrizaurAnimation
	dw SilvazurAnimation
	dw KarozurAnimation
	dw MewtwoPlainAnimation
	dw MewAnimation
	dw KoaleafAnimation
	dw EucoalaAnimation
	dw KoalyptusAnimation
	dw PyrooAnimation
	dw PyrobyAnimation
	dw WallaroAnimation
	dw PattleAnimation
	dw PlattailAnimation
	dw TsunamicAnimation
	dw FluffoonAnimation
	dw AviroonAnimation
	dw FlishAnimation
	dw VolcronicAnimation
	dw FirantAnimation
	dw PyreignAnimation
	dw CentitoeAnimation
	dw CentiliskAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuPlainAnimation
	dw HierarkAnimation
	dw AumosAnimation
	dw LapriAnimation
	dw AntartickAnimation
	dw GriAnimation
	dw RioguaAnimation
	dw FlariosAnimation
	dw DraetherAnimation
	dw TerreltaAnimation
	dw PambooAnimation
	dw SharoglyphAnimation
	dw ParlefAnimation
	dw MirustAnimation
	dw FerrianAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw CosmionAnimation
	dw AstrolionAnimation
	dw FelareAnimation
	dw ApollyonAnimation
	dw SlowkingPlainAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw UnownAAnimation
	dw ManatonAnimation
	dw DestadoAnimation
	dw KorsingAnimation
	dw SandasmaAnimation
	dw DunsparceAnimation
	dw ViperraAnimation
	dw VolterraAnimation
	dw SteelixAnimation
	dw LeefAnimation
	dw BigleefAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw QuartzellAnimation
	dw HeracrossAnimation
	dw BorinAnimation
	dw BoringlerAnimation
	dw RhinoltAnimation
	dw ThunderosAnimation
	dw GloliAnimation
	dw BizzapAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw MisticadeAnimation
	dw TarseerAnimation
	dw TarsayerAnimation
	dw SkalloyAnimation
	dw SkarmoryAnimation
	dw ZebriteAnimation
	dw ZauroraAnimation
	dw TsunallAnimation
	dw ZentaurAnimation
	dw ZagitariusAnimation
	dw DingrowlAnimation
	dw ThylereAnimation
	dw SmeargleAnimation
	dw PluppyPlainAnimation
	dw HermogAnimation
	dw FlickleAnimation
	dw MarakeAnimation
	dw ShiraAnimation
	dw SolidraAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw FercoaAnimation
	dw FercoatylAnimation
	dw FerazonAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw InferatrisAnimation
	dw WombolAnimation
	dw TarphaltPlainAnimation
	assert_table_length NUM_POKEMON

	dw EggAnimation

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw ArbokKantoAnimation
	dw ArbokKogaAnimation
	dw ArbokAgathaAnimation
	dw ArbokArianaAnimation

	dw PikachuFlyAnimation
	dw PikachuSurfAnimation
	dw PikachuPikaAnimation
	dw PikachuChuchuAnimation
	dw PikachuSparkAnimation

	dw PichuSpikyAnimation

	dw MagikarpSkellyAnimation
	dw MagikarpCalico1Animation
	dw MagikarpCalico2Animation
	dw MagikarpCalico3Animation
	dw MagikarpTwoToneAnimation
	dw MagikarpOrcaAnimation
	dw MagikarpDapplesAnimation
	dw MagikarpTigerAnimation
	dw MagikarpZebraAnimation
	dw MagikarpStripeAnimation
	dw MagikarpBubblesAnimation
	dw MagikarpForeheadAnimation
	dw MagikarpMaskAnimation
	dw MagikarpSaucyAnimation
	dw MagikarpRaindropAnimation

	dw GyaradosRedAnimation
	dw MewtwoArmoredAnimation
	dw RattataAlolanAnimation
	dw RaticateAlolanAnimation
	dw SandshrewAlolanAnimation
	dw SandslashAlolanAnimation
	dw VulpixAlolanAnimation
	dw NinetalesAlolanAnimation
	dw DiglettAlolanAnimation
	dw DugtrioAlolanAnimation
	dw OofoeAlolanAnimation
	dw XterrestreAlolanAnimation
	dw GeodudeAlolanAnimation
	dw GravelerAlolanAnimation
	dw GolemAlolanAnimation
	dw GrimerAlolanAnimation
	dw MukAlolanAnimation
	dw RaichuAlolanAnimation
	dw ExeggutorAlolanAnimation
	dw MarowakAlolanAnimation
	dw PonytaGalarianAnimation
	dw RapidashGalarianAnimation
	dw SlowpokeGalarianAnimation
	dw SlowbroGalarianAnimation
	dw SlowkingGalarianAnimation
	dw WeezingGalarianAnimation
	dw ArticunoGalarianAnimation
	dw ZapdosGalarianAnimation
	dw MoltresGalarianAnimation
	dw PluppyGalarianAnimation
	dw TarphaltGalarianAnimation

	assert_table_length NUM_UNIQUE_POKEMON
