PicAnimations:

BulbasaurAnimation:  INCLUDE "gfx/pokemon/bulbasaur/anim0.asm"
IvysaurAnimation:    INCLUDE "gfx/pokemon/ivysaur/anim0.asm"
ForresaurAnimation:  INCLUDE "gfx/pokemon/forresaur/anim0.asm"
CharmanderAnimation: INCLUDE "gfx/pokemon/charmander/anim0.asm"
CharmeleonAnimation: INCLUDE "gfx/pokemon/charmeleon/anim0.asm"
CharcoaltAnimation:  INCLUDE "gfx/pokemon/charcoalt/anim0.asm"
SquirtleAnimation:   INCLUDE "gfx/pokemon/squirtle/anim0.asm"
WartortleAnimation:  INCLUDE "gfx/pokemon/wartortle/anim0.asm"
RainerAnimation:     INCLUDE "gfx/pokemon/rainer/anim0.asm"
GlowurmAnimation:    INCLUDE "gfx/pokemon/glowurm/anim0.asm"
ChrysalunaAnimation: INCLUDE "gfx/pokemon/chrysaluna/anim0.asm"
LunaflyAnimation:    INCLUDE "gfx/pokemon/lunafly/anim0.asm"
MininjaAnimation:    INCLUDE "gfx/pokemon/mininja/anim0.asm"
MidoninjaAnimation:  INCLUDE "gfx/pokemon/midoninja/anim0.asm"
KushinobiAnimation:  INCLUDE "gfx/pokemon/kushinobi/anim0.asm"
PipunAnimation:      INCLUDE "gfx/pokemon/pipun/anim0.asm"
PipawkAnimation:     INCLUDE "gfx/pokemon/pipawk/anim0.asm"
PeregrandeAnimation: INCLUDE "gfx/pokemon/peregrande/anim0.asm"
LepskiAnimation:     INCLUDE "gfx/pokemon/lepski/anim0.asm"
RabalancheAnimation: INCLUDE "gfx/pokemon/rabalanche/anim0.asm"
EkansAnimation:      INCLUDE "gfx/pokemon/ekans/anim0.asm"
KelppAnimation:      INCLUDE "gfx/pokemon/kelpp/anim0.asm"
SetistaAnimation:    INCLUDE "gfx/pokemon/setista/anim0.asm"
FarcystisAnimation:  INCLUDE "gfx/pokemon/farcystis/anim0.asm"
TottemAnimation:     INCLUDE "gfx/pokemon/tottem/anim0.asm"
TototemAnimation:    INCLUDE "gfx/pokemon/tototem/anim0.asm"
TotowerAnimation:    INCLUDE "gfx/pokemon/totower/anim0.asm"
ToulavAnimation:     INCLUDE "gfx/pokemon/toulav/anim0.asm"
VollavAnimation:     INCLUDE "gfx/pokemon/vollav/anim0.asm"
LunelleAnimation:    INCLUDE "gfx/pokemon/lunelle/anim0.asm"
GazalaxyAnimation:   INCLUDE "gfx/pokemon/gazalaxy/anim0.asm"
ZubatAnimation:      INCLUDE "gfx/pokemon/zubat/anim0.asm"
GolbatAnimation:     INCLUDE "gfx/pokemon/golbat/anim0.asm"
SpirikAnimation:     INCLUDE "gfx/pokemon/spirik/anim0.asm"
SpirrentAnimation:   INCLUDE "gfx/pokemon/spirrent/anim0.asm"
GhobraAnimation:     INCLUDE "gfx/pokemon/ghobra/anim0.asm"
AmirokAnimation:     INCLUDE "gfx/pokemon/amirok/anim0.asm"
KiyarokAnimation:    INCLUDE "gfx/pokemon/kiyarok/anim0.asm"
VenonatAnimation:    INCLUDE "gfx/pokemon/venonat/anim0.asm"
VenomothAnimation:   INCLUDE "gfx/pokemon/venomoth/anim0.asm"
OntlamAnimation:     INCLUDE "gfx/pokemon/ontlam/anim0.asm"
BlizzaramAnimation:  INCLUDE "gfx/pokemon/blizzaram/anim0.asm"
TaegleAnimation:     INCLUDE "gfx/pokemon/taegle/anim0.asm"
TaloniteAnimation:   INCLUDE "gfx/pokemon/talonite/anim0.asm"
ShreekAnimation:     INCLUDE "gfx/pokemon/shreek/anim0.asm"
JestauntAnimation:   INCLUDE "gfx/pokemon/jestaunt/anim0.asm"
TaroxinAnimation:    INCLUDE "gfx/pokemon/taroxin/anim0.asm"
SauroxicAnimation:   INCLUDE "gfx/pokemon/sauroxic/anim0.asm"
ChatotAnimation:     INCLUDE "gfx/pokemon/chatot/anim0.asm"
MiraiAnimation:      INCLUDE "gfx/pokemon/mirai/anim0.asm"
MiralupeAnimation:   INCLUDE "gfx/pokemon/miralupe/anim0.asm"
MiralairAnimation:   INCLUDE "gfx/pokemon/miralair/anim0.asm"
SnarligerAnimation:  INCLUDE "gfx/pokemon/snarliger/anim0.asm"
NoctigerAnimation:   INCLUDE "gfx/pokemon/noctiger/anim0.asm"
RaigerAnimation:     INCLUDE "gfx/pokemon/raiger/anim0.asm"
VenapAnimation:      INCLUDE "gfx/pokemon/venap/anim0.asm"
TraplentAnimation:   INCLUDE "gfx/pokemon/traplent/anim0.asm"
DionareAnimation:    INCLUDE "gfx/pokemon/dionare/anim0.asm"
TentacoolAnimation:  INCLUDE "gfx/pokemon/tentacool/anim0.asm"
TentacruelAnimation: INCLUDE "gfx/pokemon/tentacruel/anim0.asm"
CumosAnimation:      INCLUDE "gfx/pokemon/cumos/anim0.asm"
AgmosAnimation:      INCLUDE "gfx/pokemon/agmos/anim0.asm"
OrclataAnimation:    INCLUDE "gfx/pokemon/orclata/anim0.asm"
SonnestAnimation:    INCLUDE "gfx/pokemon/sonnest/anim0.asm"
CanarosaAnimation:   INCLUDE "gfx/pokemon/canarosa/anim0.asm"
SygnalAnimation:     INCLUDE "gfx/pokemon/sygnal/anim0.asm"
SwanamiAnimation:    INCLUDE "gfx/pokemon/swanami/anim0.asm"
ShellderAnimation:   INCLUDE "gfx/pokemon/shellder/anim0.asm"
CloysterAnimation:   INCLUDE "gfx/pokemon/cloyster/anim0.asm"
ChitangAnimation:    INCLUDE "gfx/pokemon/chitang/anim0.asm"
KudangAnimation:     INCLUDE "gfx/pokemon/kudang/anim0.asm"
TerrangAnimation:    INCLUDE "gfx/pokemon/terrang/anim0.asm"
OnixAnimation:       INCLUDE "gfx/pokemon/onix/anim0.asm"
InfermataAnimation:  INCLUDE "gfx/pokemon/infermata/anim0.asm"
ClarimataAnimation:  INCLUDE "gfx/pokemon/clarimata/anim0.asm"
TyookAnimation:      INCLUDE "gfx/pokemon/tyook/anim0.asm"
MorterrorAnimation:  INCLUDE "gfx/pokemon/morterror/anim0.asm"
VoltotAnimation:     INCLUDE "gfx/pokemon/voltot/anim0.asm"
ToxicellAnimation:   INCLUDE "gfx/pokemon/toxicell/anim0.asm"
ExeggcuteAnimation:  INCLUDE "gfx/pokemon/exeggcute/anim0.asm"
CuboneAnimation:     INCLUDE "gfx/pokemon/cubone/anim0.asm"
MalistrilAnimation:  INCLUDE "gfx/pokemon/malistril/anim0.asm"
KipporokAnimation:   INCLUDE "gfx/pokemon/kipporok/anim0.asm"
KoffingAnimation:    INCLUDE "gfx/pokemon/koffing/anim0.asm"
PsibianAnimation:    INCLUDE "gfx/pokemon/psibian/anim0.asm"
GorphibiusAnimation: INCLUDE "gfx/pokemon/gorphibius/anim0.asm"
ChanseyAnimation:    INCLUDE "gfx/pokemon/chansey/anim0.asm"
DunviathanAnimation: INCLUDE "gfx/pokemon/dunviathan/anim0.asm"
VolphinAnimation:    INCLUDE "gfx/pokemon/volphin/anim0.asm"
AquonyAnimation:     INCLUDE "gfx/pokemon/aquony/anim0.asm"
AquallionAnimation:  INCLUDE "gfx/pokemon/aquallion/anim0.asm"
PhairisAnimation:    INCLUDE "gfx/pokemon/phairis/anim0.asm"
SprimaAnimation:     INCLUDE "gfx/pokemon/sprima/anim0.asm"
DrylacAnimation:     INCLUDE "gfx/pokemon/drylac/anim0.asm"
AbsolAnimation:      INCLUDE "gfx/pokemon/absol/anim0.asm"
AbsognoAnimation:    INCLUDE "gfx/pokemon/absogno/anim0.asm"
SerinaviAnimation:   INCLUDE "gfx/pokemon/serinavi/anim0.asm"
ScytherAnimation:    INCLUDE "gfx/pokemon/scyther/anim0.asm"
KaramaAnimation:     INCLUDE "gfx/pokemon/karama/anim0.asm"
FlarakeAnimation:    INCLUDE "gfx/pokemon/flarake/anim0.asm"
HelidraAnimation:    INCLUDE "gfx/pokemon/helidra/anim0.asm"
BrahmosAnimation:    INCLUDE "gfx/pokemon/brahmos/anim0.asm"
TaurosAnimation:     INCLUDE "gfx/pokemon/tauros/anim0.asm"
LaprasAnimation:     INCLUDE "gfx/pokemon/lapras/anim0.asm"
DittoAnimation:      INCLUDE "gfx/pokemon/ditto/anim0.asm"
IonAnimation:        INCLUDE "gfx/pokemon/ion/anim0.asm"
SolarionAnimation:   INCLUDE "gfx/pokemon/solarion/anim0.asm"
LunarionAnimation:   INCLUDE "gfx/pokemon/lunarion/anim0.asm"
NebulionAnimation:   INCLUDE "gfx/pokemon/nebulion/anim0.asm"
AditankAnimation:    INCLUDE "gfx/pokemon/aditank/anim0.asm"
InfastegoAnimation:  INCLUDE "gfx/pokemon/infastego/anim0.asm"
LethastegoAnimation: INCLUDE "gfx/pokemon/lethastego/anim0.asm"
AnkyloAnimation:     INCLUDE "gfx/pokemon/ankylo/anim0.asm"
AnkyledgeAnimation:  INCLUDE "gfx/pokemon/ankyledge/anim0.asm"
GolothAnimation:     INCLUDE "gfx/pokemon/goloth/anim0.asm"
IllumbraAnimation:   INCLUDE "gfx/pokemon/illumbra/anim0.asm"
BrizaurAnimation:    INCLUDE "gfx/pokemon/brizaur/anim0.asm"
SilvazurAnimation:   INCLUDE "gfx/pokemon/silvazur/anim0.asm"
KarozurAnimation:    INCLUDE "gfx/pokemon/karozur/anim0.asm"
MewAnimation:        INCLUDE "gfx/pokemon/mew/anim0.asm"
KoaleafAnimation:    INCLUDE "gfx/pokemon/koaleaf/anim0.asm"
EucoalaAnimation:    INCLUDE "gfx/pokemon/eucoala/anim0.asm"
KoalyptusAnimation:  INCLUDE "gfx/pokemon/koalyptus/anim0.asm"
PyrooAnimation:      INCLUDE "gfx/pokemon/pyroo/anim0.asm"
PyrobyAnimation:     INCLUDE "gfx/pokemon/pyroby/anim0.asm"
WallaroAnimation:    INCLUDE "gfx/pokemon/wallaro/anim0.asm"
PattleAnimation:     INCLUDE "gfx/pokemon/pattle/anim0.asm"
PlattailAnimation:   INCLUDE "gfx/pokemon/plattail/anim0.asm"
TsunamicAnimation:   INCLUDE "gfx/pokemon/tsunamic/anim0.asm"
FluffoonAnimation:   INCLUDE "gfx/pokemon/fluffoon/anim0.asm"
AviroonAnimation:    INCLUDE "gfx/pokemon/aviroon/anim0.asm"
FlishAnimation:      INCLUDE "gfx/pokemon/flish/anim0.asm"
VolcronicAnimation:  INCLUDE "gfx/pokemon/volcronic/anim0.asm"
FirantAnimation:     INCLUDE "gfx/pokemon/firant/anim0.asm"
PyreignAnimation:    INCLUDE "gfx/pokemon/pyreign/anim0.asm"
CentitoeAnimation:   INCLUDE "gfx/pokemon/centitoe/anim0.asm"
CentiliskAnimation:  INCLUDE "gfx/pokemon/centilisk/anim0.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim0.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim0.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim0.asm"
HierarkAnimation:    INCLUDE "gfx/pokemon/hierark/anim0.asm"
AumosAnimation:      INCLUDE "gfx/pokemon/aumos/anim0.asm"
LapriAnimation:      INCLUDE "gfx/pokemon/lapri/anim0.asm"
AntartickAnimation:  INCLUDE "gfx/pokemon/antartick/anim0.asm"
GriAnimation:        INCLUDE "gfx/pokemon/gri/anim0.asm"
RioguaAnimation:     INCLUDE "gfx/pokemon/riogua/anim0.asm"
FlariosAnimation:    INCLUDE "gfx/pokemon/flarios/anim0.asm"
DraetherAnimation:   INCLUDE "gfx/pokemon/draether/anim0.asm"
TerreltaAnimation:   INCLUDE "gfx/pokemon/terrelta/anim0.asm"
PambooAnimation:     INCLUDE "gfx/pokemon/pamboo/anim0.asm"
SharoglyphAnimation: INCLUDE "gfx/pokemon/sharoglyph/anim0.asm"
ParlefAnimation:     INCLUDE "gfx/pokemon/parlef/anim0.asm"
MirustAnimation:     INCLUDE "gfx/pokemon/mirust/anim0.asm"
FerrianAnimation:    INCLUDE "gfx/pokemon/ferrian/anim0.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim0.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim0.asm"
WooperAnimation:     INCLUDE "gfx/pokemon/wooper/anim0.asm"
QuagsireAnimation:   INCLUDE "gfx/pokemon/quagsire/anim0.asm"
CosmionAnimation:    INCLUDE "gfx/pokemon/cosmion/anim0.asm"
AstrolionAnimation:  INCLUDE "gfx/pokemon/astrolion/anim0.asm"
FelareAnimation:     INCLUDE "gfx/pokemon/felare/anim0.asm"
ApollyonAnimation:   INCLUDE "gfx/pokemon/apollyon/anim0.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim0.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim0.asm"
ManatonAnimation:    INCLUDE "gfx/pokemon/manaton/anim0.asm"
DestadoAnimation:    INCLUDE "gfx/pokemon/destado/anim0.asm"
KorsingAnimation:    INCLUDE "gfx/pokemon/korsing/anim0.asm"
SandasmaAnimation:   INCLUDE "gfx/pokemon/sandasma/anim0.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim0.asm"
ViperraAnimation:    INCLUDE "gfx/pokemon/viperra/anim0.asm"
VolterraAnimation:   INCLUDE "gfx/pokemon/volterra/anim0.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim0.asm"
LeefAnimation:       INCLUDE "gfx/pokemon/leef/anim0.asm"
BigleefAnimation:    INCLUDE "gfx/pokemon/bigleef/anim0.asm"
QwilfishAnimation:   INCLUDE "gfx/pokemon/qwilfish/anim0.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim0.asm"
QuartzellAnimation:  INCLUDE "gfx/pokemon/quartzell/anim0.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim0.asm"
BorinAnimation:      INCLUDE "gfx/pokemon/borin/anim0.asm"
BoringlerAnimation:  INCLUDE "gfx/pokemon/boringler/anim0.asm"
RhinoltAnimation:    INCLUDE "gfx/pokemon/rhinolt/anim0.asm"
ThunderosAnimation:  INCLUDE "gfx/pokemon/thunderos/anim0.asm"
GloliAnimation:      INCLUDE "gfx/pokemon/gloli/anim0.asm"
BizzapAnimation:     INCLUDE "gfx/pokemon/bizzap/anim0.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim0.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim0.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim0.asm"
MisticadeAnimation:  INCLUDE "gfx/pokemon/misticade/anim0.asm"
TarseerAnimation:    INCLUDE "gfx/pokemon/tarseer/anim0.asm"
TarsayerAnimation:   INCLUDE "gfx/pokemon/tarsayer/anim0.asm"
SkalloyAnimation:    INCLUDE "gfx/pokemon/skalloy/anim0.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim0.asm"
ZebriteAnimation:    INCLUDE "gfx/pokemon/zebrite/anim0.asm"
ZauroraAnimation:    INCLUDE "gfx/pokemon/zaurora/anim0.asm"
TsunallAnimation:    INCLUDE "gfx/pokemon/tsunall/anim0.asm"
ZentaurAnimation:    INCLUDE "gfx/pokemon/zentaur/anim0.asm"
ZagitariusAnimation: INCLUDE "gfx/pokemon/zagitarius/anim0.asm"
DingrowlAnimation:   INCLUDE "gfx/pokemon/dingrowl/anim0.asm"
ThylereAnimation:    INCLUDE "gfx/pokemon/thylere/anim0.asm"
SmeargleAnimation:   INCLUDE "gfx/pokemon/smeargle/anim0.asm"
HermogAnimation:     INCLUDE "gfx/pokemon/hermog/anim0.asm"
FlickleAnimation:    INCLUDE "gfx/pokemon/flickle/anim0.asm"
MarakeAnimation:     INCLUDE "gfx/pokemon/marake/anim0.asm"
ShiraAnimation:      INCLUDE "gfx/pokemon/shira/anim0.asm"
SolidraAnimation:    INCLUDE "gfx/pokemon/solidra/anim0.asm"
MiltankAnimation:    INCLUDE "gfx/pokemon/miltank/anim0.asm"
BlisseyAnimation:    INCLUDE "gfx/pokemon/blissey/anim0.asm"
RaikouAnimation:     INCLUDE "gfx/pokemon/raikou/anim0.asm"
EnteiAnimation:      INCLUDE "gfx/pokemon/entei/anim0.asm"
SuicuneAnimation:    INCLUDE "gfx/pokemon/suicune/anim0.asm"
FercoaAnimation:     INCLUDE "gfx/pokemon/fercoa/anim0.asm"
FercoatylAnimation:  INCLUDE "gfx/pokemon/fercoatyl/anim0.asm"
FerazonAnimation:    INCLUDE "gfx/pokemon/ferazon/anim0.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim0.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim0.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim0.asm"
InferatrisAnimation: INCLUDE "gfx/pokemon/inferatris/anim0.asm"
WombolAnimation:     INCLUDE "gfx/pokemon/wombol/anim0.asm"
EggAnimation:        INCLUDE "gfx/pokemon/egg/anim0.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim0.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim0.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim0.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim0.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim0.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim0.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim0.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim0.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim0.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim0.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim0.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim0.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim0.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim0.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim0.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim0.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim0.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim0.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim0.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim0.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim0.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim0.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim0.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim0.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim0.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim0.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim0.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim0.asm"

PikachuPlainAnimation:  INCLUDE "gfx/pokemon/pikachu_plain/anim0.asm"
PikachuFlyAnimation:    INCLUDE "gfx/pokemon/pikachu_fly/anim0.asm"
PikachuSurfAnimation:   INCLUDE "gfx/pokemon/pikachu_surf/anim0.asm"
PikachuPikaAnimation:   INCLUDE "gfx/pokemon/pikachu_pika/anim0.asm"
PikachuChuchuAnimation: INCLUDE "gfx/pokemon/pikachu_chuchu/anim0.asm"
PikachuSparkAnimation:  INCLUDE "gfx/pokemon/pikachu_spark/anim0.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim0.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim0.asm"

ArbokJohtoAnimation:  INCLUDE "gfx/pokemon/arbok_johto/anim0.asm"
ArbokKantoAnimation:  INCLUDE "gfx/pokemon/arbok_kanto/anim0.asm"
ArbokKogaAnimation:   INCLUDE "gfx/pokemon/arbok_koga/anim0.asm"
ArbokAgathaAnimation: INCLUDE "gfx/pokemon/arbok_agatha/anim0.asm"
ArbokArianaAnimation: INCLUDE "gfx/pokemon/arbok_ariana/anim0.asm"

MagikarpPlainAnimation:
MagikarpSkellyAnimation:
MagikarpCalico1Animation:
MagikarpCalico2Animation:
MagikarpCalico3Animation:
MagikarpTwoToneAnimation:
MagikarpOrcaAnimation:
MagikarpDapplesAnimation:
MagikarpTigerAnimation:
MagikarpZebraAnimation:
MagikarpStripeAnimation:
MagikarpBubblesAnimation:
MagikarpForeheadAnimation:
MagikarpMaskAnimation:
MagikarpSaucyAnimation:
MagikarpRaindropAnimation: INCLUDE "gfx/pokemon/magikarp/anim0.asm"

GyaradosPlainAnimation: INCLUDE "gfx/pokemon/gyarados_plain/anim0.asm"
GyaradosRedAnimation:   INCLUDE "gfx/pokemon/gyarados_red/anim0.asm"

MewtwoPlainAnimation:   INCLUDE "gfx/pokemon/mewtwo_plain/anim0.asm"
MewtwoArmoredAnimation: INCLUDE "gfx/pokemon/mewtwo_armored/anim0.asm"

RattataPlainAnimation:  INCLUDE "gfx/pokemon/rattata_plain/anim0.asm"
RattataAlolanAnimation: INCLUDE "gfx/pokemon/rattata_alolan/anim0.asm"

RaticatePlainAnimation:  INCLUDE "gfx/pokemon/raticate_plain/anim0.asm"
RaticateAlolanAnimation: INCLUDE "gfx/pokemon/raticate_alolan/anim0.asm"

SandshrewPlainAnimation:  INCLUDE "gfx/pokemon/sandshrew_plain/anim0.asm"
SandshrewAlolanAnimation: INCLUDE "gfx/pokemon/sandshrew_alolan/anim0.asm"

SandslashPlainAnimation:  INCLUDE "gfx/pokemon/sandslash_plain/anim0.asm"
SandslashAlolanAnimation: INCLUDE "gfx/pokemon/sandslash_alolan/anim0.asm"

VulpixPlainAnimation:  INCLUDE "gfx/pokemon/vulpix_plain/anim0.asm"
VulpixAlolanAnimation: INCLUDE "gfx/pokemon/vulpix_alolan/anim0.asm"

NinetalesPlainAnimation:  INCLUDE "gfx/pokemon/ninetales_plain/anim0.asm"
NinetalesAlolanAnimation: INCLUDE "gfx/pokemon/ninetales_alolan/anim0.asm"

DiglettPlainAnimation:  INCLUDE "gfx/pokemon/diglett_plain/anim0.asm"
DiglettAlolanAnimation: INCLUDE "gfx/pokemon/diglett_alolan/anim0.asm"

DugtrioPlainAnimation:  INCLUDE "gfx/pokemon/dugtrio_plain/anim0.asm"
DugtrioAlolanAnimation: INCLUDE "gfx/pokemon/dugtrio_alolan/anim0.asm"

OofoePlainAnimation:  INCLUDE "gfx/pokemon/oofoe_plain/anim0.asm"
OofoeAlolanAnimation:  INCLUDE "gfx/pokemon/oofoe_alolan/anim0.asm"

XterrestrePlainAnimation:  INCLUDE "gfx/pokemon/xterrestre_plain/anim0.asm"
XterrestreAlolanAnimation:  INCLUDE "gfx/pokemon/xterrestre_alolan/anim0.asm"

GeodudePlainAnimation:  INCLUDE "gfx/pokemon/geodude_plain/anim0.asm"
GeodudeAlolanAnimation: INCLUDE "gfx/pokemon/geodude_alolan/anim0.asm"

GravelerPlainAnimation:  INCLUDE "gfx/pokemon/graveler_plain/anim0.asm"
GravelerAlolanAnimation: INCLUDE "gfx/pokemon/graveler_alolan/anim0.asm"

GolemPlainAnimation:  INCLUDE "gfx/pokemon/golem_plain/anim0.asm"
GolemAlolanAnimation: INCLUDE "gfx/pokemon/golem_alolan/anim0.asm"

GrimerPlainAnimation:  INCLUDE "gfx/pokemon/grimer_plain/anim0.asm"
GrimerAlolanAnimation: INCLUDE "gfx/pokemon/grimer_alolan/anim0.asm"

MukPlainAnimation:  INCLUDE "gfx/pokemon/muk_plain/anim0.asm"
MukAlolanAnimation: INCLUDE "gfx/pokemon/muk_alolan/anim0.asm"

RaichuPlainAnimation:  INCLUDE "gfx/pokemon/raichu_plain/anim0.asm"
RaichuAlolanAnimation: INCLUDE "gfx/pokemon/raichu_alolan/anim0.asm"

ExeggutorPlainAnimation:  INCLUDE "gfx/pokemon/exeggutor_plain/anim0.asm"
ExeggutorAlolanAnimation: INCLUDE "gfx/pokemon/exeggutor_alolan/anim0.asm"

MarowakPlainAnimation:  INCLUDE "gfx/pokemon/marowak_plain/anim0.asm"
MarowakAlolanAnimation: INCLUDE "gfx/pokemon/marowak_alolan/anim0.asm"

PonytaPlainAnimation:    INCLUDE "gfx/pokemon/ponyta_plain/anim0.asm"
PonytaGalarianAnimation: INCLUDE "gfx/pokemon/ponyta_galarian/anim0.asm"

RapidashPlainAnimation:    INCLUDE "gfx/pokemon/rapidash_plain/anim0.asm"
RapidashGalarianAnimation: INCLUDE "gfx/pokemon/rapidash_galarian/anim0.asm"

SlowpokePlainAnimation:   INCLUDE "gfx/pokemon/slowpoke_plain/anim0.asm"
SlowpokeGalarianAnimation: INCLUDE "gfx/pokemon/slowpoke_galarian/anim0.asm"

SlowbroPlainAnimation:    INCLUDE "gfx/pokemon/slowbro_plain/anim0.asm"
SlowbroGalarianAnimation: INCLUDE "gfx/pokemon/slowbro_galarian/anim0.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim0.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim0.asm"

WeezingPlainAnimation:    INCLUDE "gfx/pokemon/weezing_plain/anim0.asm"
WeezingGalarianAnimation: INCLUDE "gfx/pokemon/weezing_galarian/anim0.asm"

ArticunoPlainAnimation:    INCLUDE "gfx/pokemon/articuno_plain/anim0.asm"
ArticunoGalarianAnimation: INCLUDE "gfx/pokemon/articuno_galarian/anim0.asm"

ZapdosPlainAnimation:    INCLUDE "gfx/pokemon/zapdos_plain/anim0.asm"
ZapdosGalarianAnimation: INCLUDE "gfx/pokemon/zapdos_galarian/anim0.asm"

MoltresPlainAnimation:    INCLUDE "gfx/pokemon/moltres_plain/anim0.asm"
MoltresGalarianAnimation: INCLUDE "gfx/pokemon/moltres_galarian/anim0.asm"

PluppyPlainAnimation:    INCLUDE "gfx/pokemon/pluppy_plain/anim0.asm"
PluppyGalarianAnimation: INCLUDE "gfx/pokemon/pluppy_galarian/anim0.asm"

TarphaltPlainAnimation:    INCLUDE "gfx/pokemon/tarphalt_plain/anim0.asm"
TarphaltGalarianAnimation: INCLUDE "gfx/pokemon/tarphalt_galarian/anim0.asm"
