BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw ForresaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharcoaltBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw RainerBitmasks
	dw GlowurmBitmasks
	dw ChrysalunaBitmasks
	dw LunaflyBitmasks
	dw MininjaBitmasks
	dw MidoninjaBitmasks
	dw KushinobiBitmasks
	dw PipunBitmasks
	dw PipawkBitmasks
	dw PeregrandeBitmasks
	dw RattataPlainBitmasks
	dw RaticatePlainBitmasks
	dw LepskiBitmasks
	dw RabalancheBitmasks
	dw EkansBitmasks
	dw ArbokJohtoBitmasks
	dw PikachuPlainBitmasks
	dw RaichuPlainBitmasks
	dw SandshrewPlainBitmasks
	dw SandslashPlainBitmasks
	dw KelppBitmasks
	dw SetistaBitmasks
	dw FarcystisBitmasks
	dw TottemBitmasks
	dw TototemBitmasks
	dw TotowerBitmasks
	dw ToulavBitmasks
	dw VollavBitmasks
	dw VulpixPlainBitmasks
	dw NinetalesPlainBitmasks
	dw LunelleBitmasks
	dw GazalaxyBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw SpirikBitmasks
	dw SpirrentBitmasks
	dw GhobraBitmasks
	dw AmirokBitmasks
	dw KiyarokBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettPlainBitmasks
	dw DugtrioPlainBitmasks
	dw OofoePlainBitmasks
	dw XterrestrePlainBitmasks
	dw OntlamBitmasks
	dw BlizzaramBitmasks
	dw TaegleBitmasks
	dw TaloniteBitmasks
	dw ShreekBitmasks
	dw JestauntBitmasks
	dw TaroxinBitmasks
	dw SauroxicBitmasks
	dw ChatotBitmasks
	dw MiraiBitmasks
	dw MiralupeBitmasks
	dw MiralairBitmasks
	dw SnarligerBitmasks
	dw NoctigerBitmasks
	dw RaigerBitmasks
	dw VenapBitmasks
	dw TraplentBitmasks
	dw DionareBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudePlainBitmasks
	dw GravelerPlainBitmasks
	dw GolemPlainBitmasks
	dw PonytaPlainBitmasks
	dw RapidashPlainBitmasks
	dw SlowpokePlainBitmasks
	dw SlowbroPlainBitmasks
	dw CumosBitmasks
	dw AgmosBitmasks
	dw OrclataBitmasks
	dw SonnestBitmasks
	dw CanarosaBitmasks
	dw SygnalBitmasks
	dw SwanamiBitmasks
	dw GrimerPlainBitmasks
	dw MukPlainBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw ChitangBitmasks
	dw KudangBitmasks
	dw TerrangBitmasks
	dw OnixBitmasks
	dw InfermataBitmasks
	dw ClarimataBitmasks
	dw TyookBitmasks
	dw MorterrorBitmasks
	dw VoltotBitmasks
	dw ToxicellBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorPlainBitmasks
	dw CuboneBitmasks
	dw MarowakPlainBitmasks
	dw MalistrilBitmasks
	dw KipporokBitmasks
	dw KoffingBitmasks
	dw WeezingPlainBitmasks
	dw PsibianBitmasks
	dw GorphibiusBitmasks
	dw ChanseyBitmasks
	dw DunviathanBitmasks
	dw VolphinBitmasks
	dw AquonyBitmasks
	dw AquallionBitmasks
	dw PhairisBitmasks
	dw SprimaBitmasks
	dw DrylacBitmasks
	dw AbsolBitmasks
	dw AbsognoBitmasks
	dw SerinaviBitmasks
	dw ScytherBitmasks
	dw KaramaBitmasks
	dw FlarakeBitmasks
	dw HelidraBitmasks
	dw BrahmosBitmasks
	dw TaurosBitmasks
	dw MagikarpPlainBitmasks
	dw GyaradosPlainBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw IonBitmasks
	dw SolarionBitmasks
	dw LunarionBitmasks
	dw NebulionBitmasks
	dw AditankBitmasks
	dw InfastegoBitmasks
	dw LethastegoBitmasks
	dw AnkyloBitmasks
	dw AnkyledgeBitmasks
	dw GolothBitmasks
	dw IllumbraBitmasks
	dw ArticunoPlainBitmasks
	dw ZapdosPlainBitmasks
	dw MoltresPlainBitmasks
	dw BrizaurBitmasks
	dw SilvazurBitmasks
	dw KarozurBitmasks
	dw MewtwoPlainBitmasks
	dw MewBitmasks
	dw KoaleafBitmasks
	dw EucoalaBitmasks
	dw KoalyptusBitmasks
	dw PyrooBitmasks
	dw PyrobyBitmasks
	dw WallaroBitmasks
	dw PattleBitmasks
	dw PlattailBitmasks
	dw TsunamicBitmasks
	dw FluffoonBitmasks
	dw AviroonBitmasks
	dw FlishBitmasks
	dw VolcronicBitmasks
	dw FirantBitmasks
	dw PyreignBitmasks
	dw CentitoeBitmasks
	dw CentiliskBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuPlainBitmasks
	dw HierarkBitmasks
	dw AumosBitmasks
	dw LapriBitmasks
	dw AntartickBitmasks
	dw GriBitmasks
	dw RioguaBitmasks
	dw FlariosBitmasks
	dw DraetherBitmasks
	dw TerreltaBitmasks
	dw PambooBitmasks
	dw SharoglyphBitmasks
	dw ParlefBitmasks
	dw MirustBitmasks
	dw FerrianBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw CosmionBitmasks
	dw AstrolionBitmasks
	dw FelareBitmasks
	dw ApollyonBitmasks
	dw SlowkingPlainBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw UnownABitmasks
	dw ManatonBitmasks
	dw DestadoBitmasks
	dw KorsingBitmasks
	dw SandasmaBitmasks
	dw DunsparceBitmasks
	dw ViperraBitmasks
	dw VolterraBitmasks
	dw SteelixBitmasks
	dw LeefBitmasks
	dw BigleefBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw QuartzellBitmasks
	dw HeracrossBitmasks
	dw BorinBitmasks
	dw BoringlerBitmasks
	dw RhinoltBitmasks
	dw ThunderosBitmasks
	dw GloliBitmasks
	dw BizzapBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw MisticadeBitmasks
	dw TarseerBitmasks
	dw TarsayerBitmasks
	dw SkalloyBitmasks
	dw SkarmoryBitmasks
	dw ZebriteBitmasks
	dw ZauroraBitmasks
	dw TsunallBitmasks
	dw ZentaurBitmasks
	dw ZagitariusBitmasks
	dw DingrowlBitmasks
	dw ThylereBitmasks
	dw SmeargleBitmasks
	dw PluppyPlainBitmasks
	dw HermogBitmasks
	dw FlickleBitmasks
	dw MarakeBitmasks
	dw ShiraBitmasks
	dw SolidraBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw FercoaBitmasks
	dw FercoatylBitmasks
	dw FerazonBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw InferatrisBitmasks
	dw WombolBitmasks
	dw TarphaltPlainBitmasks
	assert_table_length NUM_POKEMON

	dw EggBitmasks

	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	dw UnownExclamationBitmasks
	dw UnownQuestionBitmasks

	dw ArbokKantoBitmasks
	dw ArbokKogaBitmasks
	dw ArbokAgathaBitmasks
	dw ArbokArianaBitmasks

	dw PikachuFlyBitmasks
	dw PikachuSurfBitmasks
	dw PikachuPikaBitmasks
	dw PikachuChuchuBitmasks
	dw PikachuSparkBitmasks

	dw PichuSpikyBitmasks

	dw MagikarpSkellyBitmasks
	dw MagikarpCalico1Bitmasks
	dw MagikarpCalico2Bitmasks
	dw MagikarpCalico3Bitmasks
	dw MagikarpTwoToneBitmasks
	dw MagikarpOrcaBitmasks
	dw MagikarpDapplesBitmasks
	dw MagikarpTigerBitmasks
	dw MagikarpZebraBitmasks
	dw MagikarpStripeBitmasks
	dw MagikarpBubblesBitmasks
	dw MagikarpForeheadBitmasks
	dw MagikarpMaskBitmasks
	dw MagikarpSaucyBitmasks
	dw MagikarpRaindropBitmasks

	dw GyaradosRedBitmasks
	dw MewtwoArmoredBitmasks
	dw RattataAlolanBitmasks
	dw RaticateAlolanBitmasks
	dw SandshrewAlolanBitmasks
	dw SandslashAlolanBitmasks
	dw VulpixAlolanBitmasks
	dw NinetalesAlolanBitmasks
	dw DiglettAlolanBitmasks
	dw DugtrioAlolanBitmasks
	dw OofoeAlolanBitmasks
	dw XterrestreAlolanBitmasks
	dw GeodudeAlolanBitmasks
	dw GravelerAlolanBitmasks
	dw GolemAlolanBitmasks
	dw GrimerAlolanBitmasks
	dw MukAlolanBitmasks
	dw RaichuAlolanBitmasks
	dw ExeggutorAlolanBitmasks
	dw MarowakAlolanBitmasks
	dw PonytaGalarianBitmasks
	dw RapidashGalarianBitmasks
	dw SlowpokeGalarianBitmasks
	dw SlowbroGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw ArticunoGalarianBitmasks
	dw ZapdosGalarianBitmasks
	dw MoltresGalarianBitmasks
	dw PluppyGalarianBitmasks
	dw TarphaltGalarianBitmasks

	assert_table_length NUM_UNIQUE_POKEMON
