AnimationExtraPointers:
	table_width 2, AnimationExtraPointers
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw ForresaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharcoaltAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw RainerAnimationExtra
	dw GlowurmAnimationExtra
	dw ChrysalunaAnimationExtra
	dw LunaflyAnimationExtra
	dw MininjaAnimationExtra
	dw MidoninjaAnimationExtra
	dw KushinobiAnimationExtra
	dw PipunAnimationExtra
	dw PipawkAnimationExtra
	dw PeregrandeAnimationExtra
	dw RattataPlainAnimationExtra
	dw RaticatePlainAnimationExtra
	dw LepskiAnimationExtra
	dw RabalancheAnimationExtra
	dw EkansAnimationExtra
	dw ArbokJohtoAnimationExtra
	dw PikachuPlainAnimationExtra
	dw RaichuPlainAnimationExtra
	dw SandshrewPlainAnimationExtra
	dw SandslashPlainAnimationExtra
	dw KelppAnimationExtra
	dw SetistaAnimationExtra
	dw FarcystisAnimationExtra
	dw TottemAnimationExtra
	dw TototemAnimationExtra
	dw TotowerAnimationExtra
	dw ToulavAnimationExtra
	dw VollavAnimationExtra
	dw VulpixPlainAnimationExtra
	dw NinetalesPlainAnimationExtra
	dw LunelleAnimationExtra
	dw GazalaxyAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw SpirikAnimationExtra
	dw SpirrentAnimationExtra
	dw GhobraAnimationExtra
	dw AmirokAnimationExtra
	dw KiyarokAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw DiglettPlainAnimationExtra
	dw DugtrioPlainAnimationExtra
	dw OofoePlainAnimationExtra
	dw XterrestrePlainAnimationExtra
	dw OntlamAnimationExtra
	dw BlizzaramAnimationExtra
	dw TaegleAnimationExtra
	dw TaloniteAnimationExtra
	dw ShreekAnimationExtra
	dw JestauntAnimationExtra
	dw TaroxinAnimationExtra
	dw SauroxicAnimationExtra
	dw ChatotAnimationExtra
	dw MiraiAnimationExtra
	dw MiralupeAnimationExtra
	dw MiralairAnimationExtra
	dw SnarligerAnimationExtra
	dw NoctigerAnimationExtra
	dw RaigerAnimationExtra
	dw VenapAnimationExtra
	dw TraplentAnimationExtra
	dw DionareAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudePlainAnimationExtra
	dw GravelerPlainAnimationExtra
	dw GolemPlainAnimationExtra
	dw PonytaPlainAnimationExtra
	dw RapidashPlainAnimationExtra
	dw SlowpokePlainAnimationExtra
	dw SlowbroPlainAnimationExtra
	dw CumosAnimationExtra
	dw AgmosAnimationExtra
	dw OrclataAnimationExtra
	dw SonnestAnimationExtra
	dw CanarosaAnimationExtra
	dw SygnalAnimationExtra
	dw SwanamiAnimationExtra
	dw GrimerPlainAnimationExtra
	dw MukPlainAnimationExtra
	dw ShellderAnimationExtra
	dw CloysterAnimationExtra
	dw ChitangAnimationExtra
	dw KudangAnimationExtra
	dw TerrangAnimationExtra
	dw OnixAnimationExtra
	dw InfermataAnimationExtra
	dw ClarimataAnimationExtra
	dw TyookAnimationExtra
	dw MorterrorAnimationExtra
	dw VoltotAnimationExtra
	dw ToxicellAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorPlainAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakPlainAnimationExtra
	dw MalistrilAnimationExtra
	dw KipporokAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingPlainAnimationExtra
	dw PsibianAnimationExtra
	dw GorphibiusAnimationExtra
	dw ChanseyAnimationExtra
	dw DunviathanAnimationExtra
	dw VolphinAnimationExtra
	dw AquonyAnimationExtra
	dw AquallionAnimationExtra
	dw PhairisAnimationExtra
	dw SprimaAnimationExtra
	dw DrylacAnimationExtra
	dw AbsolAnimationExtra
	dw AbsognoAnimationExtra
	dw SerinaviAnimationExtra
	dw ScytherAnimationExtra
	dw KaramaAnimationExtra
	dw FlarakeAnimationExtra
	dw HelidraAnimationExtra
	dw BrahmosAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpPlainAnimationExtra
	dw GyaradosPlainAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw IonAnimationExtra
	dw SolarionAnimationExtra
	dw LunarionAnimationExtra
	dw NebulionAnimationExtra
	dw AditankAnimationExtra
	dw InfastegoAnimationExtra
	dw LethastegoAnimationExtra
	dw AnkyloAnimationExtra
	dw AnkyledgeAnimationExtra
	dw GolothAnimationExtra
	dw IllumbraAnimationExtra
	dw ArticunoPlainAnimationExtra
	dw ZapdosPlainAnimationExtra
	dw MoltresPlainAnimationExtra
	dw BrizaurAnimationExtra
	dw SilvazurAnimationExtra
	dw KarozurAnimationExtra
	dw MewtwoPlainAnimationExtra
	dw MewAnimationExtra
	dw KoaleafAnimationExtra
	dw EucoalaAnimationExtra
	dw KoalyptusAnimationExtra
	dw PyrooAnimationExtra
	dw PyrobyAnimationExtra
	dw WallaroAnimationExtra
	dw PattleAnimationExtra
	dw PlattailAnimationExtra
	dw TsunamicAnimationExtra
	dw FluffoonAnimationExtra
	dw AviroonAnimationExtra
	dw FlishAnimationExtra
	dw VolcronicAnimationExtra
	dw FirantAnimationExtra
	dw PyreignAnimationExtra
	dw CentitoeAnimationExtra
	dw CentiliskAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuPlainAnimationExtra
	dw HierarkAnimationExtra
	dw AumosAnimationExtra
	dw LapriAnimationExtra
	dw AntartickAnimationExtra
	dw GriAnimationExtra
	dw RioguaAnimationExtra
	dw FlariosAnimationExtra
	dw DraetherAnimationExtra
	dw TerreltaAnimationExtra
	dw PambooAnimationExtra
	dw SharoglyphAnimationExtra
	dw ParlefAnimationExtra
	dw MirustAnimationExtra
	dw FerrianAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw CosmionAnimationExtra
	dw AstrolionAnimationExtra
	dw FelareAnimationExtra
	dw ApollyonAnimationExtra
	dw SlowkingPlainAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw UnownAAnimationExtra
	dw ManatonAnimationExtra
	dw DestadoAnimationExtra
	dw KorsingAnimationExtra
	dw SandasmaAnimationExtra
	dw DunsparceAnimationExtra
	dw ViperraAnimationExtra
	dw VolterraAnimationExtra
	dw SteelixAnimationExtra
	dw LeefAnimationExtra
	dw BigleefAnimationExtra
	dw QwilfishAnimationExtra
	dw ScizorAnimationExtra
	dw QuartzellAnimationExtra
	dw HeracrossAnimationExtra
	dw BorinAnimationExtra
	dw BoringlerAnimationExtra
	dw RhinoltAnimationExtra
	dw ThunderosAnimationExtra
	dw GloliAnimationExtra
	dw BizzapAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw MamoswineAnimationExtra
	dw MisticadeAnimationExtra
	dw TarseerAnimationExtra
	dw TarsayerAnimationExtra
	dw SkalloyAnimationExtra
	dw SkarmoryAnimationExtra
	dw ZebriteAnimationExtra
	dw ZauroraAnimationExtra
	dw TsunallAnimationExtra
	dw ZentaurAnimationExtra
	dw ZagitariusAnimationExtra
	dw DingrowlAnimationExtra
	dw ThylereAnimationExtra
	dw SmeargleAnimationExtra
	dw PluppyPlainAnimationExtra
	dw HermogAnimationExtra
	dw FlickleAnimationExtra
	dw MarakeAnimationExtra
	dw ShiraAnimationExtra
	dw SolidraAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw FercoaAnimationExtra
	dw FercoatylAnimationExtra
	dw FerazonAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw InferatrisAnimationExtra
	dw WombolAnimationExtra
	dw TarphaltPlainAnimationExtra
	assert_table_length NUM_POKEMON

	dw EggAnimationExtra

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw ArbokKantoAnimationExtra
	dw ArbokKogaAnimationExtra
	dw ArbokAgathaAnimationExtra
	dw ArbokArianaAnimationExtra

	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra
	dw PikachuSparkAnimationExtra

	dw PichuSpikyAnimationExtra

	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpForeheadAnimationExtra
	dw MagikarpMaskAnimationExtra
	dw MagikarpSaucyAnimationExtra
	dw MagikarpRaindropAnimationExtra

	dw GyaradosRedAnimationExtra
	dw MewtwoArmoredAnimationExtra
	dw RattataAlolanAnimationExtra
	dw RaticateAlolanAnimationExtra
	dw SandshrewAlolanAnimationExtra
	dw SandslashAlolanAnimationExtra
	dw VulpixAlolanAnimationExtra
	dw NinetalesAlolanAnimationExtra
	dw DiglettAlolanAnimationExtra
	dw DugtrioAlolanAnimationExtra
	dw OofoeAlolanAnimationExtra
	dw XterrestreAlolanAnimationExtra
	dw GeodudeAlolanAnimationExtra
	dw GravelerAlolanAnimationExtra
	dw GolemAlolanAnimationExtra
	dw GrimerAlolanAnimationExtra
	dw MukAlolanAnimationExtra
	dw RaichuAlolanAnimationExtra
	dw ExeggutorAlolanAnimationExtra
	dw MarowakAlolanAnimationExtra
	dw PonytaGalarianAnimationExtra
	dw RapidashGalarianAnimationExtra
	dw SlowpokeGalarianAnimationExtra
	dw SlowbroGalarianAnimationExtra
	dw SlowkingGalarianAnimationExtra
	dw WeezingGalarianAnimationExtra
	dw ArticunoGalarianAnimationExtra
	dw ZapdosGalarianAnimationExtra
	dw MoltresGalarianAnimationExtra
	dw PluppyGalarianAnimationExtra
	dw TarphaltGalarianAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
