BulbasaurAnimationExtra:  INCLUDE "gfx/pokemon/bulbasaur/anim1.asm"
IvysaurAnimationExtra:    INCLUDE "gfx/pokemon/ivysaur/anim1.asm"
ForresaurAnimationExtra:  INCLUDE "gfx/pokemon/forresaur/anim1.asm"
CharmanderAnimationExtra: INCLUDE "gfx/pokemon/charmander/anim1.asm"
CharmeleonAnimationExtra: INCLUDE "gfx/pokemon/charmeleon/anim1.asm"
CharcoaltAnimationExtra:  INCLUDE "gfx/pokemon/charcoalt/anim1.asm"
SquirtleAnimationExtra:   INCLUDE "gfx/pokemon/squirtle/anim1.asm"
WartortleAnimationExtra:  INCLUDE "gfx/pokemon/wartortle/anim1.asm"
RainerAnimationExtra:     INCLUDE "gfx/pokemon/rainer/anim1.asm"
GlowurmAnimationExtra:    INCLUDE "gfx/pokemon/glowurm/anim1.asm"
ChrysalunaAnimationExtra: INCLUDE "gfx/pokemon/chrysaluna/anim1.asm"
LunaflyAnimationExtra:    INCLUDE "gfx/pokemon/lunafly/anim1.asm"
MininjaAnimationExtra:    INCLUDE "gfx/pokemon/mininja/anim1.asm"
MidoninjaAnimationExtra:  INCLUDE "gfx/pokemon/midoninja/anim1.asm"
KushinobiAnimationExtra:  INCLUDE "gfx/pokemon/kushinobi/anim1.asm"
PipunAnimationExtra:      INCLUDE "gfx/pokemon/pipun/anim1.asm"
PipawkAnimationExtra:     INCLUDE "gfx/pokemon/pipawk/anim1.asm"
PeregrandeAnimationExtra: INCLUDE "gfx/pokemon/peregrande/anim1.asm"
LepskiAnimationExtra:     INCLUDE "gfx/pokemon/lepski/anim1.asm"
RabalancheAnimationExtra: INCLUDE "gfx/pokemon/rabalanche/anim1.asm"
EkansAnimationExtra:      INCLUDE "gfx/pokemon/ekans/anim1.asm"
KelppAnimationExtra:      INCLUDE "gfx/pokemon/kelpp/anim1.asm"
SetistaAnimationExtra:    INCLUDE "gfx/pokemon/setista/anim1.asm"
FarcystisAnimationExtra:  INCLUDE "gfx/pokemon/farcystis/anim1.asm"
TottemAnimationExtra:     INCLUDE "gfx/pokemon/tottem/anim1.asm"
TototemAnimationExtra:    INCLUDE "gfx/pokemon/tototem/anim1.asm"
TotowerAnimationExtra:    INCLUDE "gfx/pokemon/totower/anim1.asm"
ToulavAnimationExtra:     INCLUDE "gfx/pokemon/toulav/anim1.asm"
VollavAnimationExtra:     INCLUDE "gfx/pokemon/vollav/anim1.asm"
LunelleAnimationExtra:    INCLUDE "gfx/pokemon/lunelle/anim1.asm"
GazalaxyAnimationExtra:   INCLUDE "gfx/pokemon/gazalaxy/anim1.asm"
ZubatAnimationExtra:      INCLUDE "gfx/pokemon/zubat/anim1.asm"
GolbatAnimationExtra:     INCLUDE "gfx/pokemon/golbat/anim1.asm"
SpirikAnimationExtra:     INCLUDE "gfx/pokemon/spirik/anim1.asm"
SpirrentAnimationExtra:   INCLUDE "gfx/pokemon/spirrent/anim1.asm"
GhobraAnimationExtra:     INCLUDE "gfx/pokemon/ghobra/anim1.asm"
AmirokAnimationExtra:     INCLUDE "gfx/pokemon/amirok/anim1.asm"
KiyarokAnimationExtra:    INCLUDE "gfx/pokemon/kiyarok/anim1.asm"
VenonatAnimationExtra:    INCLUDE "gfx/pokemon/venonat/anim1.asm"
VenomothAnimationExtra:   INCLUDE "gfx/pokemon/venomoth/anim1.asm"
OntlamAnimationExtra:     INCLUDE "gfx/pokemon/ontlam/anim1.asm"
BlizzaramAnimationExtra:  INCLUDE "gfx/pokemon/blizzaram/anim1.asm"
TaegleAnimationExtra:     INCLUDE "gfx/pokemon/taegle/anim1.asm"
TaloniteAnimationExtra:   INCLUDE "gfx/pokemon/talonite/anim1.asm"
ShreekAnimationExtra:     INCLUDE "gfx/pokemon/shreek/anim1.asm"
JestauntAnimationExtra:   INCLUDE "gfx/pokemon/jestaunt/anim1.asm"
TaroxinAnimationExtra:    INCLUDE "gfx/pokemon/taroxin/anim1.asm"
SauroxicAnimationExtra:   INCLUDE "gfx/pokemon/sauroxic/anim1.asm"
ChatotAnimationExtra:     INCLUDE "gfx/pokemon/chatot/anim1.asm"
MiraiAnimationExtra:      INCLUDE "gfx/pokemon/mirai/anim1.asm"
MiralupeAnimationExtra:   INCLUDE "gfx/pokemon/miralupe/anim1.asm"
MiralairAnimationExtra:   INCLUDE "gfx/pokemon/miralair/anim1.asm"
SnarligerAnimationExtra:  INCLUDE "gfx/pokemon/snarliger/anim1.asm"
NoctigerAnimationExtra:   INCLUDE "gfx/pokemon/noctiger/anim1.asm"
RaigerAnimationExtra:     INCLUDE "gfx/pokemon/raiger/anim1.asm"
VenapAnimationExtra:      INCLUDE "gfx/pokemon/venap/anim1.asm"
TraplentAnimationExtra:   INCLUDE "gfx/pokemon/traplent/anim1.asm"
DionareAnimationExtra:    INCLUDE "gfx/pokemon/dionare/anim1.asm"
TentacoolAnimationExtra:  INCLUDE "gfx/pokemon/tentacool/anim1.asm"
TentacruelAnimationExtra: INCLUDE "gfx/pokemon/tentacruel/anim1.asm"
CumosAnimationExtra:      INCLUDE "gfx/pokemon/cumos/anim1.asm"
AgmosAnimationExtra:      INCLUDE "gfx/pokemon/agmos/anim1.asm"
OrclataAnimationExtra:    INCLUDE "gfx/pokemon/orclata/anim1.asm"
SonnestAnimationExtra:    INCLUDE "gfx/pokemon/sonnest/anim1.asm"
CanarosaAnimationExtra:   INCLUDE "gfx/pokemon/canarosa/anim1.asm"
SygnalAnimationExtra:     INCLUDE "gfx/pokemon/sygnal/anim1.asm"
SwanamiAnimationExtra:    INCLUDE "gfx/pokemon/swanami/anim1.asm"
ShellderAnimationExtra:   INCLUDE "gfx/pokemon/shellder/anim1.asm"
CloysterAnimationExtra:   INCLUDE "gfx/pokemon/cloyster/anim1.asm"
ChitangAnimationExtra:    INCLUDE "gfx/pokemon/chitang/anim1.asm"
KudangAnimationExtra:     INCLUDE "gfx/pokemon/kudang/anim1.asm"
TerrangAnimationExtra:    INCLUDE "gfx/pokemon/terrang/anim1.asm"
OnixAnimationExtra:       INCLUDE "gfx/pokemon/onix/anim1.asm"
InfermataAnimationExtra:  INCLUDE "gfx/pokemon/infermata/anim1.asm"
ClarimataAnimationExtra:  INCLUDE "gfx/pokemon/clarimata/anim1.asm"
TyookAnimationExtra:      INCLUDE "gfx/pokemon/tyook/anim1.asm"
MorterrorAnimationExtra:  INCLUDE "gfx/pokemon/morterror/anim1.asm"
VoltotAnimationExtra:     INCLUDE "gfx/pokemon/voltot/anim1.asm"
ToxicellAnimationExtra:   INCLUDE "gfx/pokemon/toxicell/anim1.asm"
ExeggcuteAnimationExtra:  INCLUDE "gfx/pokemon/exeggcute/anim1.asm"
CuboneAnimationExtra:     INCLUDE "gfx/pokemon/cubone/anim1.asm"
MalistrilAnimationExtra:  INCLUDE "gfx/pokemon/malistril/anim1.asm"
KipporokAnimationExtra:   INCLUDE "gfx/pokemon/kipporok/anim1.asm"
KoffingAnimationExtra:    INCLUDE "gfx/pokemon/koffing/anim1.asm"
PsibianAnimationExtra:    INCLUDE "gfx/pokemon/psibian/anim1.asm"
GorphibiusAnimationExtra: INCLUDE "gfx/pokemon/gorphibius/anim1.asm"
ChanseyAnimationExtra:    INCLUDE "gfx/pokemon/chansey/anim1.asm"
DunviathanAnimationExtra: INCLUDE "gfx/pokemon/dunviathan/anim1.asm"
VolphinAnimationExtra:    INCLUDE "gfx/pokemon/volphin/anim1.asm"
AquonyAnimationExtra:     INCLUDE "gfx/pokemon/aquony/anim1.asm"
AquallionAnimationExtra:  INCLUDE "gfx/pokemon/aquallion/anim1.asm"
PhairisAnimationExtra:    INCLUDE "gfx/pokemon/phairis/anim1.asm"
SprimaAnimationExtra:     INCLUDE "gfx/pokemon/sprima/anim1.asm"
DrylacAnimationExtra:     INCLUDE "gfx/pokemon/drylac/anim1.asm"
AbsolAnimationExtra:      INCLUDE "gfx/pokemon/absol/anim1.asm"
AbsognoAnimationExtra:    INCLUDE "gfx/pokemon/absogno/anim1.asm"
SerinaviAnimationExtra:   INCLUDE "gfx/pokemon/serinavi/anim1.asm"
ScytherAnimationExtra:    INCLUDE "gfx/pokemon/scyther/anim1.asm"
KaramaAnimationExtra:     INCLUDE "gfx/pokemon/karama/anim1.asm"
FlarakeAnimationExtra:    INCLUDE "gfx/pokemon/flarake/anim1.asm"
HelidraAnimationExtra:    INCLUDE "gfx/pokemon/helidra/anim1.asm"
BrahmosAnimationExtra:    INCLUDE "gfx/pokemon/brahmos/anim1.asm"
TaurosAnimationExtra:     INCLUDE "gfx/pokemon/tauros/anim1.asm"
LaprasAnimationExtra:     INCLUDE "gfx/pokemon/lapras/anim1.asm"
DittoAnimationExtra:      INCLUDE "gfx/pokemon/ditto/anim1.asm"
IonAnimationExtra:        INCLUDE "gfx/pokemon/ion/anim1.asm"
SolarionAnimationExtra:   INCLUDE "gfx/pokemon/solarion/anim1.asm"
LunarionAnimationExtra:   INCLUDE "gfx/pokemon/lunarion/anim1.asm"
NebulionAnimationExtra:   INCLUDE "gfx/pokemon/nebulion/anim1.asm"
AditankAnimationExtra:    INCLUDE "gfx/pokemon/aditank/anim1.asm"
InfastegoAnimationExtra:  INCLUDE "gfx/pokemon/infastego/anim1.asm"
LethastegoAnimationExtra: INCLUDE "gfx/pokemon/lethastego/anim1.asm"
AnkyloAnimationExtra:     INCLUDE "gfx/pokemon/ankylo/anim1.asm"
AnkyledgeAnimationExtra:  INCLUDE "gfx/pokemon/ankyledge/anim1.asm"
GolothAnimationExtra:     INCLUDE "gfx/pokemon/goloth/anim1.asm"
IllumbraAnimationExtra:   INCLUDE "gfx/pokemon/illumbra/anim1.asm"
BrizaurAnimationExtra:    INCLUDE "gfx/pokemon/brizaur/anim1.asm"
SilvazurAnimationExtra:   INCLUDE "gfx/pokemon/silvazur/anim1.asm"
KarozurAnimationExtra:    INCLUDE "gfx/pokemon/karozur/anim1.asm"
MewAnimationExtra:        INCLUDE "gfx/pokemon/mew/anim1.asm"
KoaleafAnimationExtra:    INCLUDE "gfx/pokemon/koaleaf/anim1.asm"
EucoalaAnimationExtra:    INCLUDE "gfx/pokemon/eucoala/anim1.asm"
KoalyptusAnimationExtra:  INCLUDE "gfx/pokemon/koalyptus/anim1.asm"
PyrooAnimationExtra:      INCLUDE "gfx/pokemon/pyroo/anim1.asm"
PyrobyAnimationExtra:     INCLUDE "gfx/pokemon/pyroby/anim1.asm"
WallaroAnimationExtra:    INCLUDE "gfx/pokemon/wallaro/anim1.asm"
PattleAnimationExtra:     INCLUDE "gfx/pokemon/pattle/anim1.asm"
PlattailAnimationExtra:   INCLUDE "gfx/pokemon/plattail/anim1.asm"
TsunamicAnimationExtra:   INCLUDE "gfx/pokemon/tsunamic/anim1.asm"
FluffoonAnimationExtra:   INCLUDE "gfx/pokemon/fluffoon/anim1.asm"
AviroonAnimationExtra:    INCLUDE "gfx/pokemon/aviroon/anim1.asm"
FlishAnimationExtra:      INCLUDE "gfx/pokemon/flish/anim1.asm"
VolcronicAnimationExtra:  INCLUDE "gfx/pokemon/volcronic/anim1.asm"
FirantAnimationExtra:     INCLUDE "gfx/pokemon/firant/anim1.asm"
PyreignAnimationExtra:    INCLUDE "gfx/pokemon/pyreign/anim1.asm"
CentitoeAnimationExtra:   INCLUDE "gfx/pokemon/centitoe/anim1.asm"
CentiliskAnimationExtra:  INCLUDE "gfx/pokemon/centilisk/anim1.asm"
CrobatAnimationExtra:     INCLUDE "gfx/pokemon/crobat/anim1.asm"
ChinchouAnimationExtra:   INCLUDE "gfx/pokemon/chinchou/anim1.asm"
LanturnAnimationExtra:    INCLUDE "gfx/pokemon/lanturn/anim1.asm"
HierarkAnimationExtra:    INCLUDE "gfx/pokemon/hierark/anim1.asm"
AumosAnimationExtra:      INCLUDE "gfx/pokemon/aumos/anim1.asm"
LapriAnimationExtra:      INCLUDE "gfx/pokemon/lapri/anim1.asm"
AntartickAnimationExtra:  INCLUDE "gfx/pokemon/antartick/anim1.asm"
GriAnimationExtra:        INCLUDE "gfx/pokemon/gri/anim1.asm"
RioguaAnimationExtra:     INCLUDE "gfx/pokemon/riogua/anim1.asm"
FlariosAnimationExtra:    INCLUDE "gfx/pokemon/flarios/anim1.asm"
DraetherAnimationExtra:   INCLUDE "gfx/pokemon/draether/anim1.asm"
TerreltaAnimationExtra:   INCLUDE "gfx/pokemon/terrelta/anim1.asm"
PambooAnimationExtra:     INCLUDE "gfx/pokemon/pamboo/anim1.asm"
SharoglyphAnimationExtra: INCLUDE "gfx/pokemon/sharoglyph/anim1.asm"
ParlefAnimationExtra:     INCLUDE "gfx/pokemon/parlef/anim1.asm"
MirustAnimationExtra:     INCLUDE "gfx/pokemon/mirust/anim1.asm"
FerrianAnimationExtra:    INCLUDE "gfx/pokemon/ferrian/anim1.asm"
YanmaAnimationExtra:      INCLUDE "gfx/pokemon/yanma/anim1.asm"
YanmegaAnimationExtra:    INCLUDE "gfx/pokemon/yanmega/anim1.asm"
WooperAnimationExtra:     INCLUDE "gfx/pokemon/wooper/anim1.asm"
QuagsireAnimationExtra:   INCLUDE "gfx/pokemon/quagsire/anim1.asm"
CosmionAnimationExtra:    INCLUDE "gfx/pokemon/cosmion/anim1.asm"
AstrolionAnimationExtra:  INCLUDE "gfx/pokemon/astrolion/anim1.asm"
FelareAnimationExtra:     INCLUDE "gfx/pokemon/felare/anim1.asm"
ApollyonAnimationExtra:   INCLUDE "gfx/pokemon/apollyon/anim1.asm"
MisdreavusAnimationExtra: INCLUDE "gfx/pokemon/misdreavus/anim1.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim1.asm"
ManatonAnimationExtra:    INCLUDE "gfx/pokemon/manaton/anim1.asm"
DestadoAnimationExtra:    INCLUDE "gfx/pokemon/destado/anim1.asm"
KorsingAnimationExtra:    INCLUDE "gfx/pokemon/korsing/anim1.asm"
SandasmaAnimationExtra:   INCLUDE "gfx/pokemon/sandasma/anim1.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim1.asm"
ViperraAnimationExtra:    INCLUDE "gfx/pokemon/viperra/anim1.asm"
VolterraAnimationExtra:   INCLUDE "gfx/pokemon/volterra/anim1.asm"
SteelixAnimationExtra:    INCLUDE "gfx/pokemon/steelix/anim1.asm"
LeefAnimationExtra:       INCLUDE "gfx/pokemon/leef/anim1.asm"
BigleefAnimationExtra:    INCLUDE "gfx/pokemon/bigleef/anim1.asm"
QwilfishAnimationExtra:   INCLUDE "gfx/pokemon/qwilfish/anim1.asm"
ScizorAnimationExtra:     INCLUDE "gfx/pokemon/scizor/anim1.asm"
QuartzellAnimationExtra:  INCLUDE "gfx/pokemon/quartzell/anim1.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim1.asm"
BorinAnimationExtra:      INCLUDE "gfx/pokemon/borin/anim1.asm"
BoringlerAnimationExtra:  INCLUDE "gfx/pokemon/boringler/anim1.asm"
RhinoltAnimationExtra:    INCLUDE "gfx/pokemon/rhinolt/anim1.asm"
ThunderosAnimationExtra:  INCLUDE "gfx/pokemon/thunderos/anim1.asm"
GloliAnimationExtra:      INCLUDE "gfx/pokemon/gloli/anim1.asm"
BizzapAnimationExtra:     INCLUDE "gfx/pokemon/bizzap/anim1.asm"
SwinubAnimationExtra:     INCLUDE "gfx/pokemon/swinub/anim1.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim1.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim1.asm"
MisticadeAnimationExtra:  INCLUDE "gfx/pokemon/misticade/anim1.asm"
TarseerAnimationExtra:    INCLUDE "gfx/pokemon/tarseer/anim1.asm"
TarsayerAnimationExtra:   INCLUDE "gfx/pokemon/tarsayer/anim1.asm"
SkalloyAnimationExtra:    INCLUDE "gfx/pokemon/skalloy/anim1.asm"
SkarmoryAnimationExtra:   INCLUDE "gfx/pokemon/skarmory/anim1.asm"
ZebriteAnimationExtra:    INCLUDE "gfx/pokemon/zebrite/anim1.asm"
ZauroraAnimationExtra:    INCLUDE "gfx/pokemon/zaurora/anim1.asm"
TsunallAnimationExtra:    INCLUDE "gfx/pokemon/tsunall/anim1.asm"
ZentaurAnimationExtra:    INCLUDE "gfx/pokemon/zentaur/anim1.asm"
ZagitariusAnimationExtra: INCLUDE "gfx/pokemon/zagitarius/anim1.asm"
DingrowlAnimationExtra:   INCLUDE "gfx/pokemon/dingrowl/anim1.asm"
ThylereAnimationExtra:    INCLUDE "gfx/pokemon/thylere/anim1.asm"
SmeargleAnimationExtra:   INCLUDE "gfx/pokemon/smeargle/anim1.asm"
HermogAnimationExtra:     INCLUDE "gfx/pokemon/hermog/anim1.asm"
FlickleAnimationExtra:    INCLUDE "gfx/pokemon/flickle/anim1.asm"
MarakeAnimationExtra:     INCLUDE "gfx/pokemon/marake/anim1.asm"
ShiraAnimationExtra:      INCLUDE "gfx/pokemon/shira/anim1.asm"
SolidraAnimationExtra:    INCLUDE "gfx/pokemon/solidra/anim1.asm"
MiltankAnimationExtra:    INCLUDE "gfx/pokemon/miltank/anim1.asm"
BlisseyAnimationExtra:    INCLUDE "gfx/pokemon/blissey/anim1.asm"
RaikouAnimationExtra:     INCLUDE "gfx/pokemon/raikou/anim1.asm"
EnteiAnimationExtra:      INCLUDE "gfx/pokemon/entei/anim1.asm"
SuicuneAnimationExtra:    INCLUDE "gfx/pokemon/suicune/anim1.asm"
FercoaAnimationExtra:     INCLUDE "gfx/pokemon/fercoa/anim1.asm"
FercoatylAnimationExtra:  INCLUDE "gfx/pokemon/fercoatyl/anim1.asm"
FerazonAnimationExtra:    INCLUDE "gfx/pokemon/ferazon/anim1.asm"
LugiaAnimationExtra:      INCLUDE "gfx/pokemon/lugia/anim1.asm"
HoOhAnimationExtra:       INCLUDE "gfx/pokemon/ho_oh/anim1.asm"
CelebiAnimationExtra:     INCLUDE "gfx/pokemon/celebi/anim1.asm"
InferatrisAnimationExtra: INCLUDE "gfx/pokemon/inferatris/anim1.asm"
WombolAnimationExtra:     INCLUDE "gfx/pokemon/wombol/anim1.asm"
EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim1.asm"

UnownAAnimationExtra: INCLUDE "gfx/pokemon/unown_a/anim1.asm"
UnownBAnimationExtra: INCLUDE "gfx/pokemon/unown_b/anim1.asm"
UnownCAnimationExtra: INCLUDE "gfx/pokemon/unown_c/anim1.asm"
UnownDAnimationExtra: INCLUDE "gfx/pokemon/unown_d/anim1.asm"
UnownEAnimationExtra: INCLUDE "gfx/pokemon/unown_e/anim1.asm"
UnownFAnimationExtra: INCLUDE "gfx/pokemon/unown_f/anim1.asm"
UnownGAnimationExtra: INCLUDE "gfx/pokemon/unown_g/anim1.asm"
UnownHAnimationExtra: INCLUDE "gfx/pokemon/unown_h/anim1.asm"
UnownIAnimationExtra: INCLUDE "gfx/pokemon/unown_i/anim1.asm"
UnownJAnimationExtra: INCLUDE "gfx/pokemon/unown_j/anim1.asm"
UnownKAnimationExtra: INCLUDE "gfx/pokemon/unown_k/anim1.asm"
UnownLAnimationExtra: INCLUDE "gfx/pokemon/unown_l/anim1.asm"
UnownMAnimationExtra: INCLUDE "gfx/pokemon/unown_m/anim1.asm"
UnownNAnimationExtra: INCLUDE "gfx/pokemon/unown_n/anim1.asm"
UnownOAnimationExtra: INCLUDE "gfx/pokemon/unown_o/anim1.asm"
UnownPAnimationExtra: INCLUDE "gfx/pokemon/unown_p/anim1.asm"
UnownQAnimationExtra: INCLUDE "gfx/pokemon/unown_q/anim1.asm"
UnownRAnimationExtra: INCLUDE "gfx/pokemon/unown_r/anim1.asm"
UnownSAnimationExtra: INCLUDE "gfx/pokemon/unown_s/anim1.asm"
UnownTAnimationExtra: INCLUDE "gfx/pokemon/unown_t/anim1.asm"
UnownUAnimationExtra: INCLUDE "gfx/pokemon/unown_u/anim1.asm"
UnownVAnimationExtra: INCLUDE "gfx/pokemon/unown_v/anim1.asm"
UnownWAnimationExtra: INCLUDE "gfx/pokemon/unown_w/anim1.asm"
UnownXAnimationExtra: INCLUDE "gfx/pokemon/unown_x/anim1.asm"
UnownYAnimationExtra: INCLUDE "gfx/pokemon/unown_y/anim1.asm"
UnownZAnimationExtra: INCLUDE "gfx/pokemon/unown_z/anim1.asm"
UnownExclamationAnimationExtra: INCLUDE "gfx/pokemon/unown_exclamation/anim1.asm"
UnownQuestionAnimationExtra:    INCLUDE "gfx/pokemon/unown_question/anim1.asm"

PichuPlainAnimationExtra: INCLUDE "gfx/pokemon/pichu_plain/anim1.asm"
PichuSpikyAnimationExtra: INCLUDE "gfx/pokemon/pichu_spiky/anim1.asm"

PikachuSparkAnimationExtra:
PikachuPlainAnimationExtra:  INCLUDE "gfx/pokemon/pikachu_plain/anim1.asm"
PikachuFlyAnimationExtra:    INCLUDE "gfx/pokemon/pikachu_fly/anim1.asm"
PikachuSurfAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_surf/anim1.asm"
PikachuPikaAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_pika/anim1.asm"
PikachuChuchuAnimationExtra: INCLUDE "gfx/pokemon/pikachu_chuchu/anim1.asm"

ArbokJohtoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_johto/anim1.asm"
ArbokKantoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_kanto/anim1.asm"
ArbokKogaAnimationExtra:   INCLUDE "gfx/pokemon/arbok_koga/anim1.asm"
ArbokAgathaAnimationExtra: INCLUDE "gfx/pokemon/arbok_agatha/anim1.asm"
ArbokArianaAnimationExtra: INCLUDE "gfx/pokemon/arbok_ariana/anim1.asm"

MagikarpPlainAnimationExtra:
MagikarpSkellyAnimationExtra:
MagikarpCalico1AnimationExtra:
MagikarpCalico2AnimationExtra:
MagikarpCalico3AnimationExtra:
MagikarpTwoToneAnimationExtra:
MagikarpOrcaAnimationExtra:
MagikarpDapplesAnimationExtra:
MagikarpTigerAnimationExtra:
MagikarpZebraAnimationExtra:
MagikarpStripeAnimationExtra:
MagikarpBubblesAnimationExtra:
MagikarpForeheadAnimationExtra:
MagikarpMaskAnimationExtra:
MagikarpSaucyAnimationExtra:
MagikarpRaindropAnimationExtra: INCLUDE "gfx/pokemon/magikarp/anim1.asm"

GyaradosPlainAnimationExtra: INCLUDE "gfx/pokemon/gyarados_plain/anim1.asm"
GyaradosRedAnimationExtra:   INCLUDE "gfx/pokemon/gyarados_red/anim1.asm"

MewtwoPlainAnimationExtra:   INCLUDE "gfx/pokemon/mewtwo_plain/anim1.asm"
MewtwoArmoredAnimationExtra: INCLUDE "gfx/pokemon/mewtwo_armored/anim1.asm"

RattataPlainAnimationExtra:  INCLUDE "gfx/pokemon/rattata_plain/anim1.asm"
RattataAlolanAnimationExtra: INCLUDE "gfx/pokemon/rattata_alolan/anim1.asm"

RaticatePlainAnimationExtra:  INCLUDE "gfx/pokemon/raticate_plain/anim1.asm"
RaticateAlolanAnimationExtra: INCLUDE "gfx/pokemon/raticate_alolan/anim1.asm"

SandshrewPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandshrew_plain/anim1.asm"
SandshrewAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandshrew_alolan/anim1.asm"

SandslashPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandslash_plain/anim1.asm"
SandslashAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandslash_alolan/anim1.asm"

VulpixPlainAnimationExtra:  INCLUDE "gfx/pokemon/vulpix_plain/anim1.asm"
VulpixAlolanAnimationExtra: INCLUDE "gfx/pokemon/vulpix_alolan/anim1.asm"

NinetalesPlainAnimationExtra:  INCLUDE "gfx/pokemon/ninetales_plain/anim1.asm"
NinetalesAlolanAnimationExtra: INCLUDE "gfx/pokemon/ninetales_alolan/anim1.asm"

DiglettPlainAnimationExtra:  INCLUDE "gfx/pokemon/diglett_plain/anim1.asm"
DiglettAlolanAnimationExtra: INCLUDE "gfx/pokemon/diglett_alolan/anim1.asm"

DugtrioPlainAnimationExtra:  INCLUDE "gfx/pokemon/dugtrio_plain/anim1.asm"
DugtrioAlolanAnimationExtra: INCLUDE "gfx/pokemon/dugtrio_alolan/anim1.asm"

OofoePlainAnimationExtra: INCLUDE "gfx/pokemon/oofoe_plain/anim1.asm"
OofoeAlolanAnimationExtra: INCLUDE "gfx/pokemon/oofoe_alolan/anim1.asm"

XterrestrePlainAnimationExtra: INCLUDE "gfx/pokemon/xterrestre_plain/anim1.asm"
XterrestreAlolanAnimationExtra: INCLUDE "gfx/pokemon/xterrestre_alolan/anim1.asm"

GeodudePlainAnimationExtra:  INCLUDE "gfx/pokemon/geodude_plain/anim1.asm"
GeodudeAlolanAnimationExtra: INCLUDE "gfx/pokemon/geodude_alolan/anim1.asm"

GravelerPlainAnimationExtra:  INCLUDE "gfx/pokemon/graveler_plain/anim1.asm"
GravelerAlolanAnimationExtra: INCLUDE "gfx/pokemon/graveler_alolan/anim1.asm"

GolemPlainAnimationExtra:  INCLUDE "gfx/pokemon/golem_plain/anim1.asm"
GolemAlolanAnimationExtra: INCLUDE "gfx/pokemon/golem_alolan/anim1.asm"

GrimerPlainAnimationExtra:  INCLUDE "gfx/pokemon/grimer_plain/anim1.asm"
GrimerAlolanAnimationExtra: INCLUDE "gfx/pokemon/grimer_alolan/anim1.asm"

MukPlainAnimationExtra:  INCLUDE "gfx/pokemon/muk_plain/anim1.asm"
MukAlolanAnimationExtra: INCLUDE "gfx/pokemon/muk_alolan/anim1.asm"

RaichuPlainAnimationExtra:  INCLUDE "gfx/pokemon/raichu_plain/anim1.asm"
RaichuAlolanAnimationExtra: INCLUDE "gfx/pokemon/raichu_alolan/anim1.asm"

ExeggutorPlainAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor_plain/anim1.asm"
ExeggutorAlolanAnimationExtra: INCLUDE "gfx/pokemon/exeggutor_alolan/anim1.asm"

MarowakPlainAnimationExtra:  INCLUDE "gfx/pokemon/marowak_plain/anim1.asm"
MarowakAlolanAnimationExtra: INCLUDE "gfx/pokemon/marowak_alolan/anim1.asm"

PonytaPlainAnimationExtra:    INCLUDE "gfx/pokemon/ponyta_plain/anim1.asm"
PonytaGalarianAnimationExtra: INCLUDE "gfx/pokemon/ponyta_galarian/anim1.asm"

RapidashPlainAnimationExtra:    INCLUDE "gfx/pokemon/rapidash_plain/anim1.asm"
RapidashGalarianAnimationExtra: INCLUDE "gfx/pokemon/rapidash_galarian/anim1.asm"

SlowpokePlainAnimationExtra:   INCLUDE "gfx/pokemon/slowpoke_plain/anim1.asm"
SlowpokeGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowpoke_galarian/anim1.asm"

SlowbroPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowbro_plain/anim1.asm"
SlowbroGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowbro_galarian/anim1.asm"

SlowkingPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowking_plain/anim1.asm"
SlowkingGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowking_galarian/anim1.asm"

WeezingPlainAnimationExtra:    INCLUDE "gfx/pokemon/weezing_plain/anim1.asm"
WeezingGalarianAnimationExtra: INCLUDE "gfx/pokemon/weezing_galarian/anim1.asm"

ArticunoPlainAnimationExtra:    INCLUDE "gfx/pokemon/articuno_plain/anim1.asm"
ArticunoGalarianAnimationExtra: INCLUDE "gfx/pokemon/articuno_galarian/anim1.asm"

ZapdosPlainAnimationExtra:    INCLUDE "gfx/pokemon/zapdos_plain/anim1.asm"
ZapdosGalarianAnimationExtra: INCLUDE "gfx/pokemon/zapdos_galarian/anim1.asm"

MoltresPlainAnimationExtra:    INCLUDE "gfx/pokemon/moltres_plain/anim1.asm"
MoltresGalarianAnimationExtra: INCLUDE "gfx/pokemon/moltres_galarian/anim1.asm"

PluppyPlainAnimationExtra:    INCLUDE "gfx/pokemon/pluppy_plain/anim1.asm"
PluppyGalarianAnimationExtra: INCLUDE "gfx/pokemon/pluppy_galarian/anim1.asm"

TarphaltPlainAnimationExtra:    INCLUDE "gfx/pokemon/tarphalt_plain/anim1.asm"
TarphaltGalarianAnimationExtra: INCLUDE "gfx/pokemon/tarphalt_galarian/anim1.asm"
