FramesPointers:
	table_width 2, FramesPointers
	dw BulbasaurFrames
	dw IvysaurFrames
	dw ForresaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharcoaltFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw RainerFrames
	dw GlowurmFrames
	dw ChrysalunaFrames
	dw LunaflyFrames
	dw MininjaFrames
	dw MidoninjaFrames
	dw KushinobiFrames
	dw PipunFrames
	dw PipawkFrames
	dw PeregrandeFrames
	dw RattataPlainFrames
	dw RaticatePlainFrames
	dw LepskiFrames
	dw RabalancheFrames
	dw EkansFrames
	dw ArbokJohtoFrames
	dw PikachuPlainFrames
	dw RaichuPlainFrames
	dw SandshrewPlainFrames
	dw SandslashPlainFrames
	dw KelppFrames
	dw SetistaFrames
	dw FarcystisFrames
	dw TottemFrames
	dw TototemFrames
	dw TotowerFrames
	dw ToulavFrames
	dw VollavFrames
	dw VulpixPlainFrames
	dw NinetalesPlainFrames
	dw LunelleFrames
	dw GazalaxyFrames
	dw ZubatFrames
	dw GolbatFrames
	dw SpirikFrames
	dw SpirrentFrames
	dw GhobraFrames
	dw AmirokFrames
	dw KiyarokFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettPlainFrames
	dw DugtrioPlainFrames
	dw OofoePlainFrames
	dw XterrestrePlainFrames
	dw OntlamFrames
	dw BlizzaramFrames
	dw TaegleFrames
	dw TaloniteFrames
	dw ShreekFrames
	dw JestauntFrames
	dw TaroxinFrames
	dw SauroxicFrames
	dw ChatotFrames
	dw MiraiFrames
	dw MiralupeFrames
	dw MiralairFrames
	dw SnarligerFrames
	dw NoctigerFrames
	dw RaigerFrames
	dw VenapFrames
	dw TraplentFrames
	dw DionareFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudePlainFrames
	dw GravelerPlainFrames
	dw GolemPlainFrames
	dw PonytaPlainFrames
	dw RapidashPlainFrames
	dw SlowpokePlainFrames
	dw SlowbroPlainFrames
	dw CumosFrames
	dw AgmosFrames
	dw OrclataFrames
	dw SonnestFrames
	dw CanarosaFrames
	dw SygnalFrames
	dw SwanamiFrames
	dw GrimerPlainFrames
	dw MukPlainFrames
	dw ShellderFrames
	dw CloysterFrames
	dw ChitangFrames
	dw KudangFrames
	dw TerrangFrames
	dw OnixFrames
	dw InfermataFrames
	dw ClarimataFrames
	dw TyookFrames
	dw MorterrorFrames
	dw VoltotFrames
	dw ToxicellFrames
	dw ExeggcuteFrames
	dw ExeggutorPlainFrames
	dw CuboneFrames
	dw MarowakPlainFrames
	dw MalistrilFrames
	dw KipporokFrames
	dw KoffingFrames
	dw WeezingPlainFrames
	dw PsibianFrames
	dw GorphibiusFrames
	dw ChanseyFrames
	dw DunviathanFrames
	dw VolphinFrames
	dw AquonyFrames
	dw AquallionFrames
	dw PhairisFrames
	dw SprimaFrames
	dw DrylacFrames
	dw AbsolFrames
	dw AbsognoFrames
	dw SerinaviFrames
	dw ScytherFrames
	dw KaramaFrames
	dw FlarakeFrames
	dw HelidraFrames
	dw BrahmosFrames
	dw TaurosFrames
	dw MagikarpPlainFrames
	dw GyaradosPlainFrames
	dw LaprasFrames
	dw DittoFrames
	dw IonFrames
	dw SolarionFrames
	dw LunarionFrames
	dw NebulionFrames
	dw AditankFrames
	dw InfastegoFrames
	dw LethastegoFrames
	dw AnkyloFrames
	dw AnkyledgeFrames
	dw GolothFrames
	dw IllumbraFrames
	dw ArticunoPlainFrames
	dw ZapdosPlainFrames
	dw MoltresPlainFrames
	dw BrizaurFrames
	dw SilvazurFrames
	dw KarozurFrames
	dw MewtwoPlainFrames
	dw MewFrames
	dw KoaleafFrames
	dw EucoalaFrames
	dw KoalyptusFrames
	dw PyrooFrames
	dw PyrobyFrames
	dw WallaroFrames
	dw PattleFrames
	dw PlattailFrames
	dw TsunamicFrames
	dw FluffoonFrames
	dw AviroonFrames
	dw FlishFrames
	dw VolcronicFrames
	dw FirantFrames
	dw PyreignFrames
	dw CentitoeFrames
	dw CentiliskFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuPlainFrames
	dw HierarkFrames
	dw AumosFrames
	dw LapriFrames
	dw AntartickFrames
	dw GriFrames
	dw RioguaFrames
	dw FlariosFrames
	dw DraetherFrames
	dw TerreltaFrames
	dw PambooFrames
	dw SharoglyphFrames
	dw ParlefFrames
	dw MirustFrames
	dw FerrianFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw CosmionFrames
	dw AstrolionFrames
	dw FelareFrames
	dw ApollyonFrames
	dw SlowkingPlainFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownAFrames
	dw ManatonFrames
	dw DestadoFrames
	dw KorsingFrames
	dw SandasmaFrames
	dw DunsparceFrames
	dw ViperraFrames
	dw VolterraFrames
	dw SteelixFrames
	dw LeefFrames
	dw BigleefFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw QuartzellFrames
	dw HeracrossFrames
	dw BorinFrames
	dw BoringlerFrames
	dw RhinoltFrames
	dw ThunderosFrames
	dw GloliFrames
	dw BizzapFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw MisticadeFrames
	dw TarseerFrames
	dw TarsayerFrames
	dw SkalloyFrames
	dw SkarmoryFrames
	dw ZebriteFrames
	dw ZauroraFrames
	dw TsunallFrames
	dw ZentaurFrames
	dw ZagitariusFrames
	dw DingrowlFrames
	dw ThylereFrames
	dw SmeargleFrames
	dw PluppyPlainFrames
	dw HermogFrames
	dw FlickleFrames
	dw MarakeFrames
	dw ShiraFrames
	dw SolidraFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw FercoaFrames
	dw FercoatylFrames
	dw FerazonFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw InferatrisFrames
	dw WombolFrames
	dw TarphaltPlainFrames
	assert_table_length NUM_POKEMON

	dw EggFrames

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames

	dw ArbokKantoFrames
	dw ArbokKogaFrames
	dw ArbokAgathaFrames
	dw ArbokArianaFrames

	dw PikachuFlyFrames
	dw PikachuSurfFrames
	dw PikachuPikaFrames
	dw PikachuChuchuFrames
	dw PikachuSparkFrames

	dw PichuSpikyFrames

	dw MagikarpSkellyFrames
	dw MagikarpCalico1Frames
	dw MagikarpCalico2Frames
	dw MagikarpCalico3Frames
	dw MagikarpTwoToneFrames
	dw MagikarpOrcaFrames
	dw MagikarpDapplesFrames
	dw MagikarpTigerFrames
	dw MagikarpZebraFrames
	dw MagikarpStripeFrames
	dw MagikarpBubblesFrames
	dw MagikarpForeheadFrames
	dw MagikarpMaskFrames
	dw MagikarpSaucyFrames
	dw MagikarpRaindropFrames

	dw GyaradosRedFrames
	dw MewtwoArmoredFrames
	dw RattataAlolanFrames
	dw RaticateAlolanFrames
	dw SandshrewAlolanFrames
	dw SandslashAlolanFrames
	dw VulpixAlolanFrames
	dw NinetalesAlolanFrames
	dw DiglettAlolanFrames
	dw DugtrioAlolanFrames
	dw OofoeAlolanFrames
	dw XterrestreAlolanFrames
	dw GeodudeAlolanFrames
	dw GravelerAlolanFrames
	dw GolemAlolanFrames
	dw GrimerAlolanFrames
	dw MukAlolanFrames
	dw RaichuAlolanFrames
	dw ExeggutorAlolanFrames
	dw MarowakAlolanFrames
	dw PonytaGalarianFrames
	dw RapidashGalarianFrames
	dw SlowpokeGalarianFrames
	dw SlowbroGalarianFrames
	dw SlowkingGalarianFrames
	dw WeezingGalarianFrames
	dw ArticunoGalarianFrames
	dw ZapdosGalarianFrames
	dw MoltresGalarianFrames
	dw PluppyGalarianFrames
	dw TarphaltGalarianFrames

	assert_table_length NUM_UNIQUE_POKEMON
