KantoFrames:

BulbasaurFrames:  INCLUDE "gfx/pokemon/bulbasaur/frames.asm"
IvysaurFrames:    INCLUDE "gfx/pokemon/ivysaur/frames.asm"
ForresaurFrames:  INCLUDE "gfx/pokemon/forresaur/frames.asm"
CharmanderFrames: INCLUDE "gfx/pokemon/charmander/frames.asm"
CharmeleonFrames: INCLUDE "gfx/pokemon/charmeleon/frames.asm"
CharcoaltFrames:  INCLUDE "gfx/pokemon/charcoalt/frames.asm"
SquirtleFrames:   INCLUDE "gfx/pokemon/squirtle/frames.asm"
WartortleFrames:  INCLUDE "gfx/pokemon/wartortle/frames.asm"
RainerFrames:     INCLUDE "gfx/pokemon/rainer/frames.asm"
GlowurmFrames:    INCLUDE "gfx/pokemon/glowurm/frames.asm"
ChrysalunaFrames: INCLUDE "gfx/pokemon/chrysaluna/frames.asm"
LunaflyFrames:    INCLUDE "gfx/pokemon/lunafly/frames.asm"
MininjaFrames:    INCLUDE "gfx/pokemon/mininja/frames.asm"
MidoninjaFrames:  INCLUDE "gfx/pokemon/midoninja/frames.asm"
KushinobiFrames:  INCLUDE "gfx/pokemon/kushinobi/frames.asm"
PipunFrames:      INCLUDE "gfx/pokemon/pipun/frames.asm"
PipawkFrames:     INCLUDE "gfx/pokemon/pipawk/frames.asm"
PeregrandeFrames: INCLUDE "gfx/pokemon/peregrande/frames.asm"
LepskiFrames:     INCLUDE "gfx/pokemon/lepski/frames.asm"
RabalancheFrames: INCLUDE "gfx/pokemon/rabalanche/frames.asm"
EkansFrames:      INCLUDE "gfx/pokemon/ekans/frames.asm"
KelppFrames:      INCLUDE "gfx/pokemon/kelpp/frames.asm"
SetistaFrames:    INCLUDE "gfx/pokemon/setista/frames.asm"
FarcystisFrames:  INCLUDE "gfx/pokemon/farcystis/frames.asm"
TottemFrames:     INCLUDE "gfx/pokemon/tottem/frames.asm"
TototemFrames:    INCLUDE "gfx/pokemon/tototem/frames.asm"
TotowerFrames:    INCLUDE "gfx/pokemon/totower/frames.asm"
ToulavFrames:     INCLUDE "gfx/pokemon/toulav/frames.asm"
VollavFrames:     INCLUDE "gfx/pokemon/vollav/frames.asm"
LunelleFrames:    INCLUDE "gfx/pokemon/lunelle/frames.asm"
GazalaxyFrames:   INCLUDE "gfx/pokemon/gazalaxy/frames.asm"
ZubatFrames:      INCLUDE "gfx/pokemon/zubat/frames.asm"
GolbatFrames:     INCLUDE "gfx/pokemon/golbat/frames.asm"
SpirikFrames:     INCLUDE "gfx/pokemon/spirik/frames.asm"
SpirrentFrames:   INCLUDE "gfx/pokemon/spirrent/frames.asm"
GhobraFrames:     INCLUDE "gfx/pokemon/ghobra/frames.asm"
AmirokFrames:     INCLUDE "gfx/pokemon/amirok/frames.asm"
KiyarokFrames:    INCLUDE "gfx/pokemon/kiyarok/frames.asm"
VenonatFrames:    INCLUDE "gfx/pokemon/venonat/frames.asm"
VenomothFrames:   INCLUDE "gfx/pokemon/venomoth/frames.asm"
OntlamFrames:     INCLUDE "gfx/pokemon/ontlam/frames.asm"
BlizzaramFrames:  INCLUDE "gfx/pokemon/blizzaram/frames.asm"
TaegleFrames:     INCLUDE "gfx/pokemon/taegle/frames.asm"
TaloniteFrames:   INCLUDE "gfx/pokemon/talonite/frames.asm"
ShreekFrames:     INCLUDE "gfx/pokemon/shreek/frames.asm"
JestauntFrames:   INCLUDE "gfx/pokemon/jestaunt/frames.asm"
TaroxinFrames:    INCLUDE "gfx/pokemon/taroxin/frames.asm"
SauroxicFrames:   INCLUDE "gfx/pokemon/sauroxic/frames.asm"
ChatotFrames:     INCLUDE "gfx/pokemon/chatot/frames.asm"
MiraiFrames:      INCLUDE "gfx/pokemon/mirai/frames.asm"
MiralupeFrames:   INCLUDE "gfx/pokemon/miralupe/frames.asm"
MiralairFrames:   INCLUDE "gfx/pokemon/miralair/frames.asm"
SnarligerFrames:  INCLUDE "gfx/pokemon/snarliger/frames.asm"
NoctigerFrames:   INCLUDE "gfx/pokemon/noctiger/frames.asm"
RaigerFrames:     INCLUDE "gfx/pokemon/raiger/frames.asm"
VenapFrames:      INCLUDE "gfx/pokemon/venap/frames.asm"
TraplentFrames:   INCLUDE "gfx/pokemon/traplent/frames.asm"
DionareFrames:    INCLUDE "gfx/pokemon/dionare/frames.asm"
TentacoolFrames:  INCLUDE "gfx/pokemon/tentacool/frames.asm"
TentacruelFrames: INCLUDE "gfx/pokemon/tentacruel/frames.asm"
CumosFrames:      INCLUDE "gfx/pokemon/cumos/frames.asm"
AgmosFrames:      INCLUDE "gfx/pokemon/agmos/frames.asm"
OrclataFrames:    INCLUDE "gfx/pokemon/orclata/frames.asm"
SonnestFrames:    INCLUDE "gfx/pokemon/sonnest/frames.asm"
CanarosaFrames:   INCLUDE "gfx/pokemon/canarosa/frames.asm"
SygnalFrames:     INCLUDE "gfx/pokemon/sygnal/frames.asm"
SwanamiFrames:    INCLUDE "gfx/pokemon/swanami/frames.asm"
ShellderFrames:   INCLUDE "gfx/pokemon/shellder/frames.asm"
CloysterFrames:   INCLUDE "gfx/pokemon/cloyster/frames.asm"
ChitangFrames:    INCLUDE "gfx/pokemon/chitang/frames.asm"
KudangFrames:     INCLUDE "gfx/pokemon/kudang/frames.asm"
TerrangFrames:    INCLUDE "gfx/pokemon/terrang/frames.asm"
OnixFrames:       INCLUDE "gfx/pokemon/onix/frames.asm"
InfermataFrames:  INCLUDE "gfx/pokemon/infermata/frames.asm"
ClarimataFrames:  INCLUDE "gfx/pokemon/clarimata/frames.asm"
TyookFrames:      INCLUDE "gfx/pokemon/tyook/frames.asm"
MorterrorFrames:  INCLUDE "gfx/pokemon/morterror/frames.asm"
VoltotFrames:     INCLUDE "gfx/pokemon/voltot/frames.asm"
ToxicellFrames:   INCLUDE "gfx/pokemon/toxicell/frames.asm"
ExeggcuteFrames:  INCLUDE "gfx/pokemon/exeggcute/frames.asm"
CuboneFrames:     INCLUDE "gfx/pokemon/cubone/frames.asm"
MalistrilFrames:  INCLUDE "gfx/pokemon/malistril/frames.asm"
KipporokFrames:   INCLUDE "gfx/pokemon/kipporok/frames.asm"
KoffingFrames:    INCLUDE "gfx/pokemon/koffing/frames.asm"
PsibianFrames:    INCLUDE "gfx/pokemon/psibian/frames.asm"
GorphibiusFrames: INCLUDE "gfx/pokemon/gorphibius/frames.asm"
ChanseyFrames:    INCLUDE "gfx/pokemon/chansey/frames.asm"
DunviathanFrames: INCLUDE "gfx/pokemon/dunviathan/frames.asm"
VolphinFrames:    INCLUDE "gfx/pokemon/volphin/frames.asm"
AquonyFrames:     INCLUDE "gfx/pokemon/aquony/frames.asm"
AquallionFrames:  INCLUDE "gfx/pokemon/aquallion/frames.asm"
PhairisFrames:    INCLUDE "gfx/pokemon/phairis/frames.asm"
SprimaFrames:     INCLUDE "gfx/pokemon/sprima/frames.asm"
DrylacFrames:     INCLUDE "gfx/pokemon/drylac/frames.asm"
AbsolFrames:      INCLUDE "gfx/pokemon/absol/frames.asm"
AbsognoFrames:    INCLUDE "gfx/pokemon/absogno/frames.asm"
SerinaviFrames:   INCLUDE "gfx/pokemon/serinavi/frames.asm"
ScytherFrames:    INCLUDE "gfx/pokemon/scyther/frames.asm"
KaramaFrames:     INCLUDE "gfx/pokemon/karama/frames.asm"
FlarakeFrames:    INCLUDE "gfx/pokemon/flarake/frames.asm"
HelidraFrames:    INCLUDE "gfx/pokemon/helidra/frames.asm"
BrahmosFrames:    INCLUDE "gfx/pokemon/brahmos/frames.asm"
TaurosFrames:     INCLUDE "gfx/pokemon/tauros/frames.asm"
LaprasFrames:     INCLUDE "gfx/pokemon/lapras/frames.asm"
DittoFrames:      INCLUDE "gfx/pokemon/ditto/frames.asm"
IonFrames:        INCLUDE "gfx/pokemon/ion/frames.asm"
SolarionFrames:   INCLUDE "gfx/pokemon/solarion/frames.asm"
LunarionFrames:   INCLUDE "gfx/pokemon/lunarion/frames.asm"
NebulionFrames:   INCLUDE "gfx/pokemon/nebulion/frames.asm"
AditankFrames:    INCLUDE "gfx/pokemon/aditank/frames.asm"
InfastegoFrames:  INCLUDE "gfx/pokemon/infastego/frames.asm"
LethastegoFrames: INCLUDE "gfx/pokemon/lethastego/frames.asm"
AnkyloFrames:     INCLUDE "gfx/pokemon/ankylo/frames.asm"
AnkyledgeFrames:  INCLUDE "gfx/pokemon/ankyledge/frames.asm"
GolothFrames:     INCLUDE "gfx/pokemon/goloth/frames.asm"
IllumbraFrames:   INCLUDE "gfx/pokemon/illumbra/frames.asm"
BrizaurFrames:    INCLUDE "gfx/pokemon/brizaur/frames.asm"
SilvazurFrames:   INCLUDE "gfx/pokemon/silvazur/frames.asm"
KarozurFrames:    INCLUDE "gfx/pokemon/karozur/frames.asm"
MewFrames:        INCLUDE "gfx/pokemon/mew/frames.asm"

PikachuPlainFrames:  INCLUDE "gfx/pokemon/pikachu_plain/frames.asm"
PikachuFlyFrames:    INCLUDE "gfx/pokemon/pikachu_fly/frames.asm"
PikachuSurfFrames:   INCLUDE "gfx/pokemon/pikachu_surf/frames.asm"
PikachuPikaFrames:   INCLUDE "gfx/pokemon/pikachu_pika/frames.asm"
PikachuChuchuFrames: INCLUDE "gfx/pokemon/pikachu_chuchu/frames.asm"
PikachuSparkFrames:  INCLUDE "gfx/pokemon/pikachu_spark/frames.asm"

ArbokJohtoFrames:  INCLUDE "gfx/pokemon/arbok_johto/frames.asm"
ArbokKantoFrames:  INCLUDE "gfx/pokemon/arbok_kanto/frames.asm"
ArbokKogaFrames:   INCLUDE "gfx/pokemon/arbok_koga/frames.asm"
ArbokAgathaFrames: INCLUDE "gfx/pokemon/arbok_agatha/frames.asm"
ArbokArianaFrames: INCLUDE "gfx/pokemon/arbok_ariana/frames.asm"

MagikarpPlainFrames:    INCLUDE "gfx/pokemon/magikarp_plain/frames.asm"
MagikarpSkellyFrames:   INCLUDE "gfx/pokemon/magikarp_skelly/frames.asm"
MagikarpCalico1Frames:  INCLUDE "gfx/pokemon/magikarp_calico1/frames.asm"
MagikarpCalico2Frames:  INCLUDE "gfx/pokemon/magikarp_calico2/frames.asm"
MagikarpCalico3Frames:  INCLUDE "gfx/pokemon/magikarp_calico3/frames.asm"
MagikarpTwoToneFrames:  INCLUDE "gfx/pokemon/magikarp_twotone/frames.asm"
MagikarpOrcaFrames:     INCLUDE "gfx/pokemon/magikarp_orca/frames.asm"
MagikarpDapplesFrames:  INCLUDE "gfx/pokemon/magikarp_dapples/frames.asm"
MagikarpTigerFrames:    INCLUDE "gfx/pokemon/magikarp_tiger/frames.asm"
MagikarpZebraFrames:    INCLUDE "gfx/pokemon/magikarp_zebra/frames.asm"
MagikarpStripeFrames:   INCLUDE "gfx/pokemon/magikarp_stripe/frames.asm"
MagikarpBubblesFrames:  INCLUDE "gfx/pokemon/magikarp_bubbles/frames.asm"
MagikarpForeheadFrames: INCLUDE "gfx/pokemon/magikarp_forehead/frames.asm"
MagikarpMaskFrames:     INCLUDE "gfx/pokemon/magikarp_mask/frames.asm"
MagikarpSaucyFrames:    INCLUDE "gfx/pokemon/magikarp_saucy/frames.asm"
MagikarpRaindropFrames: INCLUDE "gfx/pokemon/magikarp_raindrop/frames.asm"

GyaradosPlainFrames: INCLUDE "gfx/pokemon/gyarados_plain/frames.asm"
GyaradosRedFrames:   INCLUDE "gfx/pokemon/gyarados_red/frames.asm"

MewtwoPlainFrames:   INCLUDE "gfx/pokemon/mewtwo_plain/frames.asm"
MewtwoArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"

RattataPlainFrames:  INCLUDE "gfx/pokemon/rattata_plain/frames.asm"
RattataAlolanFrames: INCLUDE "gfx/pokemon/rattata_alolan/frames.asm"

RaticatePlainFrames:  INCLUDE "gfx/pokemon/raticate_plain/frames.asm"
RaticateAlolanFrames: INCLUDE "gfx/pokemon/raticate_alolan/frames.asm"

SandshrewPlainFrames:  INCLUDE "gfx/pokemon/sandshrew_plain/frames.asm"
SandshrewAlolanFrames: INCLUDE "gfx/pokemon/sandshrew_alolan/frames.asm"

SandslashPlainFrames:  INCLUDE "gfx/pokemon/sandslash_plain/frames.asm"
SandslashAlolanFrames: INCLUDE "gfx/pokemon/sandslash_alolan/frames.asm"

VulpixPlainFrames:  INCLUDE "gfx/pokemon/vulpix_plain/frames.asm"
VulpixAlolanFrames: INCLUDE "gfx/pokemon/vulpix_alolan/frames.asm"

NinetalesPlainFrames:  INCLUDE "gfx/pokemon/ninetales_plain/frames.asm"
NinetalesAlolanFrames: INCLUDE "gfx/pokemon/ninetales_alolan/frames.asm"

DiglettPlainFrames:  INCLUDE "gfx/pokemon/diglett_plain/frames.asm"
DiglettAlolanFrames: INCLUDE "gfx/pokemon/diglett_alolan/frames.asm"

DugtrioPlainFrames:  INCLUDE "gfx/pokemon/dugtrio_plain/frames.asm"
DugtrioAlolanFrames: INCLUDE "gfx/pokemon/dugtrio_alolan/frames.asm"

OofoePlainFrames:  INCLUDE "gfx/pokemon/oofoe_plain/frames.asm"
OofoeAlolanFrames:  INCLUDE "gfx/pokemon/oofoe_alolan/frames.asm"

XterrestrePlainFrames: INCLUDE "gfx/pokemon/xterrestre_plain/frames.asm"
XterrestreAlolanFrames: INCLUDE "gfx/pokemon/xterrestre_alolan/frames.asm"

GeodudePlainFrames:  INCLUDE "gfx/pokemon/geodude_plain/frames.asm"
GeodudeAlolanFrames: INCLUDE "gfx/pokemon/geodude_alolan/frames.asm"

GravelerPlainFrames:  INCLUDE "gfx/pokemon/graveler_plain/frames.asm"
GravelerAlolanFrames: INCLUDE "gfx/pokemon/graveler_alolan/frames.asm"

GolemPlainFrames:  INCLUDE "gfx/pokemon/golem_plain/frames.asm"
GolemAlolanFrames: INCLUDE "gfx/pokemon/golem_alolan/frames.asm"

GrimerPlainFrames:  INCLUDE "gfx/pokemon/grimer_plain/frames.asm"
GrimerAlolanFrames: INCLUDE "gfx/pokemon/grimer_alolan/frames.asm"

MukPlainFrames:  INCLUDE "gfx/pokemon/muk_plain/frames.asm"
MukAlolanFrames: INCLUDE "gfx/pokemon/muk_alolan/frames.asm"

RaichuPlainFrames:  INCLUDE "gfx/pokemon/raichu_plain/frames.asm"
RaichuAlolanFrames: INCLUDE "gfx/pokemon/raichu_alolan/frames.asm"

ExeggutorPlainFrames:  INCLUDE "gfx/pokemon/exeggutor_plain/frames.asm"
ExeggutorAlolanFrames: INCLUDE "gfx/pokemon/exeggutor_alolan/frames.asm"

MarowakPlainFrames:  INCLUDE "gfx/pokemon/marowak_plain/frames.asm"
MarowakAlolanFrames: INCLUDE "gfx/pokemon/marowak_alolan/frames.asm"

PonytaPlainFrames:    INCLUDE "gfx/pokemon/ponyta_plain/frames.asm"
PonytaGalarianFrames: INCLUDE "gfx/pokemon/ponyta_galarian/frames.asm"

RapidashPlainFrames:    INCLUDE "gfx/pokemon/rapidash_plain/frames.asm"
RapidashGalarianFrames: INCLUDE "gfx/pokemon/rapidash_galarian/frames.asm"

SlowpokePlainFrames:   INCLUDE "gfx/pokemon/slowpoke_plain/frames.asm"
SlowpokeGalarianFrames: INCLUDE "gfx/pokemon/slowpoke_galarian/frames.asm"

SlowbroPlainFrames:    INCLUDE "gfx/pokemon/slowbro_plain/frames.asm"
SlowbroGalarianFrames: INCLUDE "gfx/pokemon/slowbro_galarian/frames.asm"

WeezingPlainFrames:    INCLUDE "gfx/pokemon/weezing_plain/frames.asm"
WeezingGalarianFrames: INCLUDE "gfx/pokemon/weezing_galarian/frames.asm"

ArticunoPlainFrames:    INCLUDE "gfx/pokemon/articuno_plain/frames.asm"
ArticunoGalarianFrames: INCLUDE "gfx/pokemon/articuno_galarian/frames.asm"

ZapdosPlainFrames:    INCLUDE "gfx/pokemon/zapdos_plain/frames.asm"
ZapdosGalarianFrames: INCLUDE "gfx/pokemon/zapdos_galarian/frames.asm"

MoltresPlainFrames:    INCLUDE "gfx/pokemon/moltres_plain/frames.asm"
MoltresGalarianFrames: INCLUDE "gfx/pokemon/moltres_galarian/frames.asm"
